stages:
  - build-and-test

default:
  image: docker.grammatech.com/rewriting/gtirb-ghidra-plugin
  tags: ["kubernetes"]

build-and-test:
  stage: build-and-test
  script:
  - echo "Building plugin..."
  # Clone GTIRB repo so you can get the Java API
  - cd ${TESTDIR}
  - git clone https://git.grammatech.com/rewriting/gtirb.git
  # Run the protocol compiler to generate Java classes from proto files
  - cd ${TESTDIR}/gtirb
  - protoc --java_out=java --proto_path=proto ./proto/*.proto
  # Run cmake to generate Java class with version information
  - mkdir ${TESTDIR}/gtirb/build
  - cd ${TESTDIR}/gtirb/build
  - cmake ../ -DGTIRB_CXX_API=OFF -DGTIRB_PY_API=OFF -DGTIRB_CL_API=OFF
  - cd ${TESTDIR}/gtirb/build/java
  - make
  # Copy in GTIRB Java API and protobuf Java lib
  - cd ${CI_PROJECT_DIR}/Gtirb
  - cp ${TESTDIR}/gtirb/build/java/gtirb_api-*.jar lib/
  - cp ${TESTDIR}/protobuf-java-${PROTOBUF_VERSION}.jar lib/
  # Build the plugin
  - gradle
  # Install in Ghidra
  - mv dist/*.zip ${GHIDRA_INSTALL_DIR}/Extensions/Ghidra/${GHIDRA_DOWNLOAD_VERSION}_Gtirb.zip
  - unzip -d ${GHIDRA_INSTALL_DIR}/Ghidra/Extensions ${GHIDRA_INSTALL_DIR}/Extensions/Ghidra/${GHIDRA_DOWNLOAD_VERSION}_Gtirb.zip
  # Run test scripts using plugin in headless mode
  - cd ${CI_PROJECT_DIR}/tests
  - ./test-import test_x64.gtirb
  - ./test-import test_ia32.gtirb
  - ./test-import test_ppc32.gtirb
  - ./test-import test_arm.gtirb
