#!/bin/bash
#
# Tests whether an import was successful by looking for an expected comment in
# the gtirb file: "main of <testfilename>". If not found, test fails.
#
#
. "$(dirname "${BASH_SOURCE[0]}")/ghidra-defs.sh"

DEFAULT_GHIDRA_FILE="test_x64.gtirb"
DEFAULT_GHIDRA_SCRIPT=DumpBookmarks.java

# Allow the test file to be set as a command line argument
# (supercedes environment variable, if there is one)
if [[ ! -z "$1" ]]; then
	GHIDRA_FILE=$1
fi

GHIDRA_FILE="${GHIDRA_FILE-$DEFAULT_GHIDRA_FILE}"
GHIDRA_SCRIPT="${GHIDRA_SCRIPT-$DEFAULT_GHIDRA_SCRIPT}"

echo ""
echo " test-import:"
echo "    Import a file, analyze it, and check for errors"
echo "       Ghidra install dir:  ${GHIDRA_INSTALL_DIR}"
echo "       Ghidra project:      ${GHIDRA_PROJECT}"
echo "       Ghidra file:         ${GHIDRA_FILE}"
echo ""

#
# Run ghidra in headless mode
# - GHIDRA_SCRIPT is supposed to be a script that dump comments
# - allow import to overwrite any program already existing with that name
# - run analyzer
# - Dump bookmarks becuase any errors would be show up there.
SCRIPT_NAME=$(basename "$GHIDRA_SCRIPT")
SCRIPT_PATH=$(dirname "$GHIDRA_SCRIPT")
mkdir -p "$GHIDRA_PROJECT"
if "$HEADLESS_LAUNCH" "$PROJECT_LOCATION" "$PROJECT_NAME" -import "$GHIDRA_FILE" \
    -scriptPath "$SCRIPT_PATH" -postScript "$SCRIPT_NAME" -overwrite \
    | tee /dev/stderr | grep -q "0 error bookmarks"; then
	exit 0
else
	echo "import failed."
	exit 1
fi
