#!/bin/bash
#
# Tests whether an import was successful by looking for an expected comment in
# the gtirb file: "main of <testfilename>". If not found, test fails.
#
#
. "$(dirname "${BASH_SOURCE[0]}")/../scripts/ghidra-defs.sh"

DEFAULT_INPUT_FILE=$(dirname "${BASH_SOURCE[0]}")/hello_x64.elf
DEFAULT_GHIDRA_SCRIPT=$(dirname "${BASH_SOURCE[0]}")/DumpBookmarks.java

# Allow the test file to be set as a command line argument
# (supercedes environment variable, if there is one)
if [[ ! -z "$1" ]]; then
	INPUT_FILE=$1
fi

INPUT_FILE="${INPUT_FILE-$DEFAULT_INPUT_FILE}"
GHIDRA_SCRIPT="${GHIDRA_SCRIPT-$DEFAULT_GHIDRA_SCRIPT}"

echo ""
echo " test-import:"
echo "    Import a file, analyze it, and check for errors"
echo "       Ghidra install dir:  ${GHIDRA_INSTALL_DIR}"
echo "       Ghidra project:      ${GHIDRA_PROJECT}"
echo "       Input file:          ${INPUT_FILE}"
echo ""

GTIRB_FILE="$INPUT_FILE"
if [[ $INPUT_FILE != *.gtirb ]]; then
    GTIRB_FILE=/tmp/test-import.gtirb
    echo "Generating gtirb file from binary: $INPUT_FILE"
    ddisasm --ir "$GTIRB_FILE" "$INPUT_FILE" || exit
    echo "Created gtirb file: $GTIRB_FILE"
    echo
fi

#
# Run ghidra in headless mode
# - GHIDRA_SCRIPT is supposed to be a script that dump comments
# - allow import to overwrite any program already existing with that name
# - run analyzer
# - Dump bookmarks because any errors would be show up there.
SCRIPT_NAME=$(basename "$GHIDRA_SCRIPT")
SCRIPT_PATH=$(realpath $(dirname "$GHIDRA_SCRIPT"))
mkdir -p "$GHIDRA_PROJECT"
ghidra_headless -import "$GTIRB_FILE" -scriptPath "$SCRIPT_PATH" \
    -postScript "$SCRIPT_NAME" | tee /dev/stderr | grep -q "0 error bookmarks"
rc=$?
if [[ $rc != 0 ]]; then
    echo "import failed."
fi
rm -f /tmp/test-import.gtirb
exit $rc
