#!/bin/bash
. "$(dirname "${BASH_SOURCE[0]}")/ghidra-defs.sh"

if [[ -z "$2" ]]; then
    echo "Usage: $0 input-binary output.gtirb"
    exit 1
fi

GHIDRA_FILE="$1"
OUTPUT_FILE="$2"
GHIDRA_SCRIPT=$(dirname "${BASH_SOURCE[0]}")/ExportGtirb.java

echo "Using Ghidra to export..."
echo "    input: $1"
echo "    output GTIRB: $2"
echo

TESTFILE_NAME=$(basename "${GHIDRA_FILE}")
SCRIPT_NAME=$(basename "${GHIDRA_SCRIPT}")
SCRIPT_PATH=$(dirname "${GHIDRA_SCRIPT}")
mkdir -p "${GHIDRA_PROJECT}"
rm -f "$OUTPUT_FILE"
if "$HEADLESS_LAUNCH" "$PROJECT_LOCATION" "$PROJECT_NAME" -import "$GHIDRA_FILE" \
    -scriptPath "$SCRIPT_PATH" -postScript "$SCRIPT_NAME" $(realpath "$OUTPUT_FILE") -overwrite \
    && [[ -f "$OUTPUT_FILE" ]]; then
	exit 0
else
	echo "Export failed."
	exit 1
fi
