// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImageByteMap.proto

package proto;

public final class ImageByteMapOuterClass {
  private ImageByteMapOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImageByteMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ImageByteMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes uuid = 1;</code>
     */
    com.google.protobuf.ByteString getUuid();

    /**
     * <code>optional .proto.ByteMap byte_map = 2;</code>
     */
    boolean hasByteMap();
    /**
     * <code>optional .proto.ByteMap byte_map = 2;</code>
     */
    proto.ByteMapOuterClass.ByteMap getByteMap();
    /**
     * <code>optional .proto.ByteMap byte_map = 2;</code>
     */
    proto.ByteMapOuterClass.ByteMapOrBuilder getByteMapOrBuilder();

    /**
     * <code>optional uint64 addr_min = 3;</code>
     */
    long getAddrMin();

    /**
     * <code>optional uint64 addr_max = 4;</code>
     */
    long getAddrMax();

    /**
     * <code>optional uint64 base_address = 5;</code>
     */
    long getBaseAddress();

    /**
     * <code>optional uint64 entry_point_address = 6;</code>
     */
    long getEntryPointAddress();
  }
  /**
   * Protobuf type {@code proto.ImageByteMap}
   */
  public  static final class ImageByteMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ImageByteMap)
      ImageByteMapOrBuilder {
    // Use ImageByteMap.newBuilder() to construct.
    private ImageByteMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageByteMap() {
      uuid_ = com.google.protobuf.ByteString.EMPTY;
      addrMin_ = 0L;
      addrMax_ = 0L;
      baseAddress_ = 0L;
      entryPointAddress_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ImageByteMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              uuid_ = input.readBytes();
              break;
            }
            case 18: {
              proto.ByteMapOuterClass.ByteMap.Builder subBuilder = null;
              if (byteMap_ != null) {
                subBuilder = byteMap_.toBuilder();
              }
              byteMap_ = input.readMessage(proto.ByteMapOuterClass.ByteMap.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(byteMap_);
                byteMap_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              addrMin_ = input.readUInt64();
              break;
            }
            case 32: {

              addrMax_ = input.readUInt64();
              break;
            }
            case 40: {

              baseAddress_ = input.readUInt64();
              break;
            }
            case 48: {

              entryPointAddress_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ImageByteMapOuterClass.internal_static_proto_ImageByteMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ImageByteMapOuterClass.internal_static_proto_ImageByteMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ImageByteMapOuterClass.ImageByteMap.class, proto.ImageByteMapOuterClass.ImageByteMap.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString uuid_;
    /**
     * <code>optional bytes uuid = 1;</code>
     */
    public com.google.protobuf.ByteString getUuid() {
      return uuid_;
    }

    public static final int BYTE_MAP_FIELD_NUMBER = 2;
    private proto.ByteMapOuterClass.ByteMap byteMap_;
    /**
     * <code>optional .proto.ByteMap byte_map = 2;</code>
     */
    public boolean hasByteMap() {
      return byteMap_ != null;
    }
    /**
     * <code>optional .proto.ByteMap byte_map = 2;</code>
     */
    public proto.ByteMapOuterClass.ByteMap getByteMap() {
      return byteMap_ == null ? proto.ByteMapOuterClass.ByteMap.getDefaultInstance() : byteMap_;
    }
    /**
     * <code>optional .proto.ByteMap byte_map = 2;</code>
     */
    public proto.ByteMapOuterClass.ByteMapOrBuilder getByteMapOrBuilder() {
      return getByteMap();
    }

    public static final int ADDR_MIN_FIELD_NUMBER = 3;
    private long addrMin_;
    /**
     * <code>optional uint64 addr_min = 3;</code>
     */
    public long getAddrMin() {
      return addrMin_;
    }

    public static final int ADDR_MAX_FIELD_NUMBER = 4;
    private long addrMax_;
    /**
     * <code>optional uint64 addr_max = 4;</code>
     */
    public long getAddrMax() {
      return addrMax_;
    }

    public static final int BASE_ADDRESS_FIELD_NUMBER = 5;
    private long baseAddress_;
    /**
     * <code>optional uint64 base_address = 5;</code>
     */
    public long getBaseAddress() {
      return baseAddress_;
    }

    public static final int ENTRY_POINT_ADDRESS_FIELD_NUMBER = 6;
    private long entryPointAddress_;
    /**
     * <code>optional uint64 entry_point_address = 6;</code>
     */
    public long getEntryPointAddress() {
      return entryPointAddress_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!uuid_.isEmpty()) {
        output.writeBytes(1, uuid_);
      }
      if (byteMap_ != null) {
        output.writeMessage(2, getByteMap());
      }
      if (addrMin_ != 0L) {
        output.writeUInt64(3, addrMin_);
      }
      if (addrMax_ != 0L) {
        output.writeUInt64(4, addrMax_);
      }
      if (baseAddress_ != 0L) {
        output.writeUInt64(5, baseAddress_);
      }
      if (entryPointAddress_ != 0L) {
        output.writeUInt64(6, entryPointAddress_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!uuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, uuid_);
      }
      if (byteMap_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getByteMap());
      }
      if (addrMin_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, addrMin_);
      }
      if (addrMax_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, addrMax_);
      }
      if (baseAddress_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, baseAddress_);
      }
      if (entryPointAddress_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, entryPointAddress_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ImageByteMapOuterClass.ImageByteMap)) {
        return super.equals(obj);
      }
      proto.ImageByteMapOuterClass.ImageByteMap other = (proto.ImageByteMapOuterClass.ImageByteMap) obj;

      boolean result = true;
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && (hasByteMap() == other.hasByteMap());
      if (hasByteMap()) {
        result = result && getByteMap()
            .equals(other.getByteMap());
      }
      result = result && (getAddrMin()
          == other.getAddrMin());
      result = result && (getAddrMax()
          == other.getAddrMax());
      result = result && (getBaseAddress()
          == other.getBaseAddress());
      result = result && (getEntryPointAddress()
          == other.getEntryPointAddress());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      if (hasByteMap()) {
        hash = (37 * hash) + BYTE_MAP_FIELD_NUMBER;
        hash = (53 * hash) + getByteMap().hashCode();
      }
      hash = (37 * hash) + ADDR_MIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAddrMin());
      hash = (37 * hash) + ADDR_MAX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAddrMax());
      hash = (37 * hash) + BASE_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBaseAddress());
      hash = (37 * hash) + ENTRY_POINT_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEntryPointAddress());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ImageByteMapOuterClass.ImageByteMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ImageByteMapOuterClass.ImageByteMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ImageByteMapOuterClass.ImageByteMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ImageByteMapOuterClass.ImageByteMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ImageByteMapOuterClass.ImageByteMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ImageByteMapOuterClass.ImageByteMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ImageByteMapOuterClass.ImageByteMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ImageByteMapOuterClass.ImageByteMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ImageByteMapOuterClass.ImageByteMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ImageByteMapOuterClass.ImageByteMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ImageByteMapOuterClass.ImageByteMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ImageByteMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ImageByteMap)
        proto.ImageByteMapOuterClass.ImageByteMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ImageByteMapOuterClass.internal_static_proto_ImageByteMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ImageByteMapOuterClass.internal_static_proto_ImageByteMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ImageByteMapOuterClass.ImageByteMap.class, proto.ImageByteMapOuterClass.ImageByteMap.Builder.class);
      }

      // Construct using proto.ImageByteMapOuterClass.ImageByteMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = com.google.protobuf.ByteString.EMPTY;

        if (byteMapBuilder_ == null) {
          byteMap_ = null;
        } else {
          byteMap_ = null;
          byteMapBuilder_ = null;
        }
        addrMin_ = 0L;

        addrMax_ = 0L;

        baseAddress_ = 0L;

        entryPointAddress_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ImageByteMapOuterClass.internal_static_proto_ImageByteMap_descriptor;
      }

      public proto.ImageByteMapOuterClass.ImageByteMap getDefaultInstanceForType() {
        return proto.ImageByteMapOuterClass.ImageByteMap.getDefaultInstance();
      }

      public proto.ImageByteMapOuterClass.ImageByteMap build() {
        proto.ImageByteMapOuterClass.ImageByteMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ImageByteMapOuterClass.ImageByteMap buildPartial() {
        proto.ImageByteMapOuterClass.ImageByteMap result = new proto.ImageByteMapOuterClass.ImageByteMap(this);
        result.uuid_ = uuid_;
        if (byteMapBuilder_ == null) {
          result.byteMap_ = byteMap_;
        } else {
          result.byteMap_ = byteMapBuilder_.build();
        }
        result.addrMin_ = addrMin_;
        result.addrMax_ = addrMax_;
        result.baseAddress_ = baseAddress_;
        result.entryPointAddress_ = entryPointAddress_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ImageByteMapOuterClass.ImageByteMap) {
          return mergeFrom((proto.ImageByteMapOuterClass.ImageByteMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ImageByteMapOuterClass.ImageByteMap other) {
        if (other == proto.ImageByteMapOuterClass.ImageByteMap.getDefaultInstance()) return this;
        if (other.getUuid() != com.google.protobuf.ByteString.EMPTY) {
          setUuid(other.getUuid());
        }
        if (other.hasByteMap()) {
          mergeByteMap(other.getByteMap());
        }
        if (other.getAddrMin() != 0L) {
          setAddrMin(other.getAddrMin());
        }
        if (other.getAddrMax() != 0L) {
          setAddrMax(other.getAddrMax());
        }
        if (other.getBaseAddress() != 0L) {
          setBaseAddress(other.getBaseAddress());
        }
        if (other.getEntryPointAddress() != 0L) {
          setEntryPointAddress(other.getEntryPointAddress());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ImageByteMapOuterClass.ImageByteMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ImageByteMapOuterClass.ImageByteMap) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes uuid = 1;</code>
       */
      public com.google.protobuf.ByteString getUuid() {
        return uuid_;
      }
      /**
       * <code>optional bytes uuid = 1;</code>
       */
      public Builder setUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes uuid = 1;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }

      private proto.ByteMapOuterClass.ByteMap byteMap_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ByteMapOuterClass.ByteMap, proto.ByteMapOuterClass.ByteMap.Builder, proto.ByteMapOuterClass.ByteMapOrBuilder> byteMapBuilder_;
      /**
       * <code>optional .proto.ByteMap byte_map = 2;</code>
       */
      public boolean hasByteMap() {
        return byteMapBuilder_ != null || byteMap_ != null;
      }
      /**
       * <code>optional .proto.ByteMap byte_map = 2;</code>
       */
      public proto.ByteMapOuterClass.ByteMap getByteMap() {
        if (byteMapBuilder_ == null) {
          return byteMap_ == null ? proto.ByteMapOuterClass.ByteMap.getDefaultInstance() : byteMap_;
        } else {
          return byteMapBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ByteMap byte_map = 2;</code>
       */
      public Builder setByteMap(proto.ByteMapOuterClass.ByteMap value) {
        if (byteMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          byteMap_ = value;
          onChanged();
        } else {
          byteMapBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ByteMap byte_map = 2;</code>
       */
      public Builder setByteMap(
          proto.ByteMapOuterClass.ByteMap.Builder builderForValue) {
        if (byteMapBuilder_ == null) {
          byteMap_ = builderForValue.build();
          onChanged();
        } else {
          byteMapBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.ByteMap byte_map = 2;</code>
       */
      public Builder mergeByteMap(proto.ByteMapOuterClass.ByteMap value) {
        if (byteMapBuilder_ == null) {
          if (byteMap_ != null) {
            byteMap_ =
              proto.ByteMapOuterClass.ByteMap.newBuilder(byteMap_).mergeFrom(value).buildPartial();
          } else {
            byteMap_ = value;
          }
          onChanged();
        } else {
          byteMapBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.ByteMap byte_map = 2;</code>
       */
      public Builder clearByteMap() {
        if (byteMapBuilder_ == null) {
          byteMap_ = null;
          onChanged();
        } else {
          byteMap_ = null;
          byteMapBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.ByteMap byte_map = 2;</code>
       */
      public proto.ByteMapOuterClass.ByteMap.Builder getByteMapBuilder() {
        
        onChanged();
        return getByteMapFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ByteMap byte_map = 2;</code>
       */
      public proto.ByteMapOuterClass.ByteMapOrBuilder getByteMapOrBuilder() {
        if (byteMapBuilder_ != null) {
          return byteMapBuilder_.getMessageOrBuilder();
        } else {
          return byteMap_ == null ?
              proto.ByteMapOuterClass.ByteMap.getDefaultInstance() : byteMap_;
        }
      }
      /**
       * <code>optional .proto.ByteMap byte_map = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ByteMapOuterClass.ByteMap, proto.ByteMapOuterClass.ByteMap.Builder, proto.ByteMapOuterClass.ByteMapOrBuilder> 
          getByteMapFieldBuilder() {
        if (byteMapBuilder_ == null) {
          byteMapBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.ByteMapOuterClass.ByteMap, proto.ByteMapOuterClass.ByteMap.Builder, proto.ByteMapOuterClass.ByteMapOrBuilder>(
                  getByteMap(),
                  getParentForChildren(),
                  isClean());
          byteMap_ = null;
        }
        return byteMapBuilder_;
      }

      private long addrMin_ ;
      /**
       * <code>optional uint64 addr_min = 3;</code>
       */
      public long getAddrMin() {
        return addrMin_;
      }
      /**
       * <code>optional uint64 addr_min = 3;</code>
       */
      public Builder setAddrMin(long value) {
        
        addrMin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 addr_min = 3;</code>
       */
      public Builder clearAddrMin() {
        
        addrMin_ = 0L;
        onChanged();
        return this;
      }

      private long addrMax_ ;
      /**
       * <code>optional uint64 addr_max = 4;</code>
       */
      public long getAddrMax() {
        return addrMax_;
      }
      /**
       * <code>optional uint64 addr_max = 4;</code>
       */
      public Builder setAddrMax(long value) {
        
        addrMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 addr_max = 4;</code>
       */
      public Builder clearAddrMax() {
        
        addrMax_ = 0L;
        onChanged();
        return this;
      }

      private long baseAddress_ ;
      /**
       * <code>optional uint64 base_address = 5;</code>
       */
      public long getBaseAddress() {
        return baseAddress_;
      }
      /**
       * <code>optional uint64 base_address = 5;</code>
       */
      public Builder setBaseAddress(long value) {
        
        baseAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 base_address = 5;</code>
       */
      public Builder clearBaseAddress() {
        
        baseAddress_ = 0L;
        onChanged();
        return this;
      }

      private long entryPointAddress_ ;
      /**
       * <code>optional uint64 entry_point_address = 6;</code>
       */
      public long getEntryPointAddress() {
        return entryPointAddress_;
      }
      /**
       * <code>optional uint64 entry_point_address = 6;</code>
       */
      public Builder setEntryPointAddress(long value) {
        
        entryPointAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 entry_point_address = 6;</code>
       */
      public Builder clearEntryPointAddress() {
        
        entryPointAddress_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ImageByteMap)
    }

    // @@protoc_insertion_point(class_scope:proto.ImageByteMap)
    private static final proto.ImageByteMapOuterClass.ImageByteMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ImageByteMapOuterClass.ImageByteMap();
    }

    public static proto.ImageByteMapOuterClass.ImageByteMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageByteMap>
        PARSER = new com.google.protobuf.AbstractParser<ImageByteMap>() {
      public ImageByteMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ImageByteMap(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImageByteMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageByteMap> getParserForType() {
      return PARSER;
    }

    public proto.ImageByteMapOuterClass.ImageByteMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ImageByteMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ImageByteMap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ImageByteMap.proto\022\005proto\032\rByteMap.pro" +
      "to\"\225\001\n\014ImageByteMap\022\014\n\004uuid\030\001 \001(\014\022 \n\010byt" +
      "e_map\030\002 \001(\0132\016.proto.ByteMap\022\020\n\010addr_min\030" +
      "\003 \001(\004\022\020\n\010addr_max\030\004 \001(\004\022\024\n\014base_address\030" +
      "\005 \001(\004\022\033\n\023entry_point_address\030\006 \001(\004b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.ByteMapOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_ImageByteMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ImageByteMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ImageByteMap_descriptor,
        new java.lang.String[] { "Uuid", "ByteMap", "AddrMin", "AddrMax", "BaseAddress", "EntryPointAddress", });
    proto.ByteMapOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
