// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IR.proto

package proto;

public final class IROuterClass {
  private IROuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IROrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.IR)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes uuid = 1;</code>
     */
    com.google.protobuf.ByteString getUuid();

    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    java.util.List<proto.ModuleOuterClass.Module> 
        getModulesList();
    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    proto.ModuleOuterClass.Module getModules(int index);
    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    int getModulesCount();
    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    java.util.List<? extends proto.ModuleOuterClass.ModuleOrBuilder> 
        getModulesOrBuilderList();
    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    proto.ModuleOuterClass.ModuleOrBuilder getModulesOrBuilder(
        int index);

    /**
     * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
     */
    boolean hasAuxDataContainer();
    /**
     * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
     */
    proto.AuxDataContainerOuterClass.AuxDataContainer getAuxDataContainer();
    /**
     * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
     */
    proto.AuxDataContainerOuterClass.AuxDataContainerOrBuilder getAuxDataContainerOrBuilder();
  }
  /**
   * Protobuf type {@code proto.IR}
   */
  public  static final class IR extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.IR)
      IROrBuilder {
    // Use IR.newBuilder() to construct.
    private IR(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IR() {
      uuid_ = com.google.protobuf.ByteString.EMPTY;
      modules_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private IR(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              uuid_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                modules_ = new java.util.ArrayList<proto.ModuleOuterClass.Module>();
                mutable_bitField0_ |= 0x00000002;
              }
              modules_.add(
                  input.readMessage(proto.ModuleOuterClass.Module.parser(), extensionRegistry));
              break;
            }
            case 34: {
              proto.AuxDataContainerOuterClass.AuxDataContainer.Builder subBuilder = null;
              if (auxDataContainer_ != null) {
                subBuilder = auxDataContainer_.toBuilder();
              }
              auxDataContainer_ = input.readMessage(proto.AuxDataContainerOuterClass.AuxDataContainer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(auxDataContainer_);
                auxDataContainer_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          modules_ = java.util.Collections.unmodifiableList(modules_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.IROuterClass.internal_static_proto_IR_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.IROuterClass.internal_static_proto_IR_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.IROuterClass.IR.class, proto.IROuterClass.IR.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString uuid_;
    /**
     * <code>optional bytes uuid = 1;</code>
     */
    public com.google.protobuf.ByteString getUuid() {
      return uuid_;
    }

    public static final int MODULES_FIELD_NUMBER = 3;
    private java.util.List<proto.ModuleOuterClass.Module> modules_;
    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    public java.util.List<proto.ModuleOuterClass.Module> getModulesList() {
      return modules_;
    }
    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    public java.util.List<? extends proto.ModuleOuterClass.ModuleOrBuilder> 
        getModulesOrBuilderList() {
      return modules_;
    }
    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    public int getModulesCount() {
      return modules_.size();
    }
    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    public proto.ModuleOuterClass.Module getModules(int index) {
      return modules_.get(index);
    }
    /**
     * <code>repeated .proto.Module modules = 3;</code>
     */
    public proto.ModuleOuterClass.ModuleOrBuilder getModulesOrBuilder(
        int index) {
      return modules_.get(index);
    }

    public static final int AUX_DATA_CONTAINER_FIELD_NUMBER = 4;
    private proto.AuxDataContainerOuterClass.AuxDataContainer auxDataContainer_;
    /**
     * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
     */
    public boolean hasAuxDataContainer() {
      return auxDataContainer_ != null;
    }
    /**
     * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
     */
    public proto.AuxDataContainerOuterClass.AuxDataContainer getAuxDataContainer() {
      return auxDataContainer_ == null ? proto.AuxDataContainerOuterClass.AuxDataContainer.getDefaultInstance() : auxDataContainer_;
    }
    /**
     * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
     */
    public proto.AuxDataContainerOuterClass.AuxDataContainerOrBuilder getAuxDataContainerOrBuilder() {
      return getAuxDataContainer();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!uuid_.isEmpty()) {
        output.writeBytes(1, uuid_);
      }
      for (int i = 0; i < modules_.size(); i++) {
        output.writeMessage(3, modules_.get(i));
      }
      if (auxDataContainer_ != null) {
        output.writeMessage(4, getAuxDataContainer());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!uuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, uuid_);
      }
      for (int i = 0; i < modules_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, modules_.get(i));
      }
      if (auxDataContainer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAuxDataContainer());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.IROuterClass.IR)) {
        return super.equals(obj);
      }
      proto.IROuterClass.IR other = (proto.IROuterClass.IR) obj;

      boolean result = true;
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && getModulesList()
          .equals(other.getModulesList());
      result = result && (hasAuxDataContainer() == other.hasAuxDataContainer());
      if (hasAuxDataContainer()) {
        result = result && getAuxDataContainer()
            .equals(other.getAuxDataContainer());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      if (getModulesCount() > 0) {
        hash = (37 * hash) + MODULES_FIELD_NUMBER;
        hash = (53 * hash) + getModulesList().hashCode();
      }
      if (hasAuxDataContainer()) {
        hash = (37 * hash) + AUX_DATA_CONTAINER_FIELD_NUMBER;
        hash = (53 * hash) + getAuxDataContainer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.IROuterClass.IR parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.IROuterClass.IR parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.IROuterClass.IR parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.IROuterClass.IR parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.IROuterClass.IR parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.IROuterClass.IR parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.IROuterClass.IR parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.IROuterClass.IR parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.IROuterClass.IR parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.IROuterClass.IR parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.IROuterClass.IR prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.IR}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.IR)
        proto.IROuterClass.IROrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.IROuterClass.internal_static_proto_IR_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.IROuterClass.internal_static_proto_IR_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.IROuterClass.IR.class, proto.IROuterClass.IR.Builder.class);
      }

      // Construct using proto.IROuterClass.IR.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getModulesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = com.google.protobuf.ByteString.EMPTY;

        if (modulesBuilder_ == null) {
          modules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          modulesBuilder_.clear();
        }
        if (auxDataContainerBuilder_ == null) {
          auxDataContainer_ = null;
        } else {
          auxDataContainer_ = null;
          auxDataContainerBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.IROuterClass.internal_static_proto_IR_descriptor;
      }

      public proto.IROuterClass.IR getDefaultInstanceForType() {
        return proto.IROuterClass.IR.getDefaultInstance();
      }

      public proto.IROuterClass.IR build() {
        proto.IROuterClass.IR result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.IROuterClass.IR buildPartial() {
        proto.IROuterClass.IR result = new proto.IROuterClass.IR(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.uuid_ = uuid_;
        if (modulesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            modules_ = java.util.Collections.unmodifiableList(modules_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.modules_ = modules_;
        } else {
          result.modules_ = modulesBuilder_.build();
        }
        if (auxDataContainerBuilder_ == null) {
          result.auxDataContainer_ = auxDataContainer_;
        } else {
          result.auxDataContainer_ = auxDataContainerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.IROuterClass.IR) {
          return mergeFrom((proto.IROuterClass.IR)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.IROuterClass.IR other) {
        if (other == proto.IROuterClass.IR.getDefaultInstance()) return this;
        if (other.getUuid() != com.google.protobuf.ByteString.EMPTY) {
          setUuid(other.getUuid());
        }
        if (modulesBuilder_ == null) {
          if (!other.modules_.isEmpty()) {
            if (modules_.isEmpty()) {
              modules_ = other.modules_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureModulesIsMutable();
              modules_.addAll(other.modules_);
            }
            onChanged();
          }
        } else {
          if (!other.modules_.isEmpty()) {
            if (modulesBuilder_.isEmpty()) {
              modulesBuilder_.dispose();
              modulesBuilder_ = null;
              modules_ = other.modules_;
              bitField0_ = (bitField0_ & ~0x00000002);
              modulesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getModulesFieldBuilder() : null;
            } else {
              modulesBuilder_.addAllMessages(other.modules_);
            }
          }
        }
        if (other.hasAuxDataContainer()) {
          mergeAuxDataContainer(other.getAuxDataContainer());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.IROuterClass.IR parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.IROuterClass.IR) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes uuid = 1;</code>
       */
      public com.google.protobuf.ByteString getUuid() {
        return uuid_;
      }
      /**
       * <code>optional bytes uuid = 1;</code>
       */
      public Builder setUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes uuid = 1;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }

      private java.util.List<proto.ModuleOuterClass.Module> modules_ =
        java.util.Collections.emptyList();
      private void ensureModulesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          modules_ = new java.util.ArrayList<proto.ModuleOuterClass.Module>(modules_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ModuleOuterClass.Module, proto.ModuleOuterClass.Module.Builder, proto.ModuleOuterClass.ModuleOrBuilder> modulesBuilder_;

      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public java.util.List<proto.ModuleOuterClass.Module> getModulesList() {
        if (modulesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(modules_);
        } else {
          return modulesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public int getModulesCount() {
        if (modulesBuilder_ == null) {
          return modules_.size();
        } else {
          return modulesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public proto.ModuleOuterClass.Module getModules(int index) {
        if (modulesBuilder_ == null) {
          return modules_.get(index);
        } else {
          return modulesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public Builder setModules(
          int index, proto.ModuleOuterClass.Module value) {
        if (modulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModulesIsMutable();
          modules_.set(index, value);
          onChanged();
        } else {
          modulesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public Builder setModules(
          int index, proto.ModuleOuterClass.Module.Builder builderForValue) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.set(index, builderForValue.build());
          onChanged();
        } else {
          modulesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public Builder addModules(proto.ModuleOuterClass.Module value) {
        if (modulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModulesIsMutable();
          modules_.add(value);
          onChanged();
        } else {
          modulesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public Builder addModules(
          int index, proto.ModuleOuterClass.Module value) {
        if (modulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureModulesIsMutable();
          modules_.add(index, value);
          onChanged();
        } else {
          modulesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public Builder addModules(
          proto.ModuleOuterClass.Module.Builder builderForValue) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.add(builderForValue.build());
          onChanged();
        } else {
          modulesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public Builder addModules(
          int index, proto.ModuleOuterClass.Module.Builder builderForValue) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.add(index, builderForValue.build());
          onChanged();
        } else {
          modulesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public Builder addAllModules(
          java.lang.Iterable<? extends proto.ModuleOuterClass.Module> values) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, modules_);
          onChanged();
        } else {
          modulesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public Builder clearModules() {
        if (modulesBuilder_ == null) {
          modules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          modulesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public Builder removeModules(int index) {
        if (modulesBuilder_ == null) {
          ensureModulesIsMutable();
          modules_.remove(index);
          onChanged();
        } else {
          modulesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public proto.ModuleOuterClass.Module.Builder getModulesBuilder(
          int index) {
        return getModulesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public proto.ModuleOuterClass.ModuleOrBuilder getModulesOrBuilder(
          int index) {
        if (modulesBuilder_ == null) {
          return modules_.get(index);  } else {
          return modulesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public java.util.List<? extends proto.ModuleOuterClass.ModuleOrBuilder> 
           getModulesOrBuilderList() {
        if (modulesBuilder_ != null) {
          return modulesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(modules_);
        }
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public proto.ModuleOuterClass.Module.Builder addModulesBuilder() {
        return getModulesFieldBuilder().addBuilder(
            proto.ModuleOuterClass.Module.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public proto.ModuleOuterClass.Module.Builder addModulesBuilder(
          int index) {
        return getModulesFieldBuilder().addBuilder(
            index, proto.ModuleOuterClass.Module.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Module modules = 3;</code>
       */
      public java.util.List<proto.ModuleOuterClass.Module.Builder> 
           getModulesBuilderList() {
        return getModulesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ModuleOuterClass.Module, proto.ModuleOuterClass.Module.Builder, proto.ModuleOuterClass.ModuleOrBuilder> 
          getModulesFieldBuilder() {
        if (modulesBuilder_ == null) {
          modulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.ModuleOuterClass.Module, proto.ModuleOuterClass.Module.Builder, proto.ModuleOuterClass.ModuleOrBuilder>(
                  modules_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          modules_ = null;
        }
        return modulesBuilder_;
      }

      private proto.AuxDataContainerOuterClass.AuxDataContainer auxDataContainer_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.AuxDataContainerOuterClass.AuxDataContainer, proto.AuxDataContainerOuterClass.AuxDataContainer.Builder, proto.AuxDataContainerOuterClass.AuxDataContainerOrBuilder> auxDataContainerBuilder_;
      /**
       * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
       */
      public boolean hasAuxDataContainer() {
        return auxDataContainerBuilder_ != null || auxDataContainer_ != null;
      }
      /**
       * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
       */
      public proto.AuxDataContainerOuterClass.AuxDataContainer getAuxDataContainer() {
        if (auxDataContainerBuilder_ == null) {
          return auxDataContainer_ == null ? proto.AuxDataContainerOuterClass.AuxDataContainer.getDefaultInstance() : auxDataContainer_;
        } else {
          return auxDataContainerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
       */
      public Builder setAuxDataContainer(proto.AuxDataContainerOuterClass.AuxDataContainer value) {
        if (auxDataContainerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          auxDataContainer_ = value;
          onChanged();
        } else {
          auxDataContainerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
       */
      public Builder setAuxDataContainer(
          proto.AuxDataContainerOuterClass.AuxDataContainer.Builder builderForValue) {
        if (auxDataContainerBuilder_ == null) {
          auxDataContainer_ = builderForValue.build();
          onChanged();
        } else {
          auxDataContainerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
       */
      public Builder mergeAuxDataContainer(proto.AuxDataContainerOuterClass.AuxDataContainer value) {
        if (auxDataContainerBuilder_ == null) {
          if (auxDataContainer_ != null) {
            auxDataContainer_ =
              proto.AuxDataContainerOuterClass.AuxDataContainer.newBuilder(auxDataContainer_).mergeFrom(value).buildPartial();
          } else {
            auxDataContainer_ = value;
          }
          onChanged();
        } else {
          auxDataContainerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
       */
      public Builder clearAuxDataContainer() {
        if (auxDataContainerBuilder_ == null) {
          auxDataContainer_ = null;
          onChanged();
        } else {
          auxDataContainer_ = null;
          auxDataContainerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
       */
      public proto.AuxDataContainerOuterClass.AuxDataContainer.Builder getAuxDataContainerBuilder() {
        
        onChanged();
        return getAuxDataContainerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
       */
      public proto.AuxDataContainerOuterClass.AuxDataContainerOrBuilder getAuxDataContainerOrBuilder() {
        if (auxDataContainerBuilder_ != null) {
          return auxDataContainerBuilder_.getMessageOrBuilder();
        } else {
          return auxDataContainer_ == null ?
              proto.AuxDataContainerOuterClass.AuxDataContainer.getDefaultInstance() : auxDataContainer_;
        }
      }
      /**
       * <code>optional .proto.AuxDataContainer aux_data_container = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.AuxDataContainerOuterClass.AuxDataContainer, proto.AuxDataContainerOuterClass.AuxDataContainer.Builder, proto.AuxDataContainerOuterClass.AuxDataContainerOrBuilder> 
          getAuxDataContainerFieldBuilder() {
        if (auxDataContainerBuilder_ == null) {
          auxDataContainerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.AuxDataContainerOuterClass.AuxDataContainer, proto.AuxDataContainerOuterClass.AuxDataContainer.Builder, proto.AuxDataContainerOuterClass.AuxDataContainerOrBuilder>(
                  getAuxDataContainer(),
                  getParentForChildren(),
                  isClean());
          auxDataContainer_ = null;
        }
        return auxDataContainerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.IR)
    }

    // @@protoc_insertion_point(class_scope:proto.IR)
    private static final proto.IROuterClass.IR DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.IROuterClass.IR();
    }

    public static proto.IROuterClass.IR getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IR>
        PARSER = new com.google.protobuf.AbstractParser<IR>() {
      public IR parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new IR(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IR> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IR> getParserForType() {
      return PARSER;
    }

    public proto.IROuterClass.IR getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_IR_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_IR_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010IR.proto\022\005proto\032\rAuxData.proto\032\026AuxDat" +
      "aContainer.proto\032\014Module.proto\"g\n\002IR\022\014\n\004" +
      "uuid\030\001 \001(\014\022\036\n\007modules\030\003 \003(\0132\r.proto.Modu" +
      "le\0223\n\022aux_data_container\030\004 \001(\0132\027.proto.A" +
      "uxDataContainerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.AuxDataOuterClass.getDescriptor(),
          proto.AuxDataContainerOuterClass.getDescriptor(),
          proto.ModuleOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_IR_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_IR_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_IR_descriptor,
        new java.lang.String[] { "Uuid", "Modules", "AuxDataContainer", });
    proto.AuxDataOuterClass.getDescriptor();
    proto.AuxDataContainerOuterClass.getDescriptor();
    proto.ModuleOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
