// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuxDataContainer.proto

package proto;


public final class AuxDataContainerOuterClass {
  private AuxDataContainerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuxDataContainerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.AuxDataContainer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
     */
    int getAuxDataCount();
    /**
     * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
     */
    boolean containsAuxData(
        java.lang.String key);
    /**
     * Use {@link #getAuxDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData>
    getAuxData();
    /**
     * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
     */
    java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData>
    getAuxDataMap();
    /**
     * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
     */

    proto.AuxDataOuterClass.AuxData getAuxDataOrDefault(
        java.lang.String key,
        proto.AuxDataOuterClass.AuxData defaultValue);
    /**
     * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
     */

    proto.AuxDataOuterClass.AuxData getAuxDataOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code proto.AuxDataContainer}
   */
  public  static final class AuxDataContainer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.AuxDataContainer)
      AuxDataContainerOrBuilder {
    // Use AuxDataContainer.newBuilder() to construct.
    private AuxDataContainer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuxDataContainer() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AuxDataContainer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                auxData_ = com.google.protobuf.MapField.newMapField(
                    AuxDataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, proto.AuxDataOuterClass.AuxData>
              auxData = input.readMessage(
                  AuxDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              auxData_.getMutableMap().put(auxData.getKey(), auxData.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.AuxDataContainerOuterClass.internal_static_proto_AuxDataContainer_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetAuxData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.AuxDataContainerOuterClass.internal_static_proto_AuxDataContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.AuxDataContainerOuterClass.AuxDataContainer.class, proto.AuxDataContainerOuterClass.AuxDataContainer.Builder.class);
    }

    public static final int AUX_DATA_FIELD_NUMBER = 1;
    private static final class AuxDataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, proto.AuxDataOuterClass.AuxData> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, proto.AuxDataOuterClass.AuxData>newDefaultInstance(
                  proto.AuxDataContainerOuterClass.internal_static_proto_AuxDataContainer_AuxDataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  proto.AuxDataOuterClass.AuxData.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, proto.AuxDataOuterClass.AuxData> auxData_;
    private com.google.protobuf.MapField<java.lang.String, proto.AuxDataOuterClass.AuxData>
    internalGetAuxData() {
      if (auxData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AuxDataDefaultEntryHolder.defaultEntry);
      }
      return auxData_;
    }

    public int getAuxDataCount() {
      return internalGetAuxData().getMap().size();
    }
    /**
     * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
     */

    public boolean containsAuxData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAuxData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAuxDataMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData> getAuxData() {
      return getAuxDataMap();
    }
    /**
     * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
     */

    public java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData> getAuxDataMap() {
      return internalGetAuxData().getMap();
    }
    /**
     * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
     */

    public proto.AuxDataOuterClass.AuxData getAuxDataOrDefault(
        java.lang.String key,
        proto.AuxDataOuterClass.AuxData defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData> map =
          internalGetAuxData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
     */

    public proto.AuxDataOuterClass.AuxData getAuxDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData> map =
          internalGetAuxData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, proto.AuxDataOuterClass.AuxData> entry
           : internalGetAuxData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, proto.AuxDataOuterClass.AuxData>
        auxData = AuxDataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, auxData);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, proto.AuxDataOuterClass.AuxData> entry
           : internalGetAuxData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, proto.AuxDataOuterClass.AuxData>
        auxData = AuxDataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, auxData);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.AuxDataContainerOuterClass.AuxDataContainer)) {
        return super.equals(obj);
      }
      proto.AuxDataContainerOuterClass.AuxDataContainer other = (proto.AuxDataContainerOuterClass.AuxDataContainer) obj;

      boolean result = true;
      result = result && internalGetAuxData().equals(
          other.internalGetAuxData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetAuxData().getMap().isEmpty()) {
        hash = (37 * hash) + AUX_DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAuxData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.AuxDataContainerOuterClass.AuxDataContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.AuxDataContainerOuterClass.AuxDataContainer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.AuxDataContainer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.AuxDataContainer)
        proto.AuxDataContainerOuterClass.AuxDataContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.AuxDataContainerOuterClass.internal_static_proto_AuxDataContainer_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetAuxData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableAuxData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.AuxDataContainerOuterClass.internal_static_proto_AuxDataContainer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.AuxDataContainerOuterClass.AuxDataContainer.class, proto.AuxDataContainerOuterClass.AuxDataContainer.Builder.class);
      }

      // Construct using proto.AuxDataContainerOuterClass.AuxDataContainer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableAuxData().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.AuxDataContainerOuterClass.internal_static_proto_AuxDataContainer_descriptor;
      }

      public proto.AuxDataContainerOuterClass.AuxDataContainer getDefaultInstanceForType() {
        return proto.AuxDataContainerOuterClass.AuxDataContainer.getDefaultInstance();
      }

      public proto.AuxDataContainerOuterClass.AuxDataContainer build() {
        proto.AuxDataContainerOuterClass.AuxDataContainer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.AuxDataContainerOuterClass.AuxDataContainer buildPartial() {
        proto.AuxDataContainerOuterClass.AuxDataContainer result = new proto.AuxDataContainerOuterClass.AuxDataContainer(this);
        int from_bitField0_ = bitField0_;
        result.auxData_ = internalGetAuxData();
        result.auxData_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.AuxDataContainerOuterClass.AuxDataContainer) {
          return mergeFrom((proto.AuxDataContainerOuterClass.AuxDataContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.AuxDataContainerOuterClass.AuxDataContainer other) {
        if (other == proto.AuxDataContainerOuterClass.AuxDataContainer.getDefaultInstance()) return this;
        internalGetMutableAuxData().mergeFrom(
            other.internalGetAuxData());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.AuxDataContainerOuterClass.AuxDataContainer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.AuxDataContainerOuterClass.AuxDataContainer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, proto.AuxDataOuterClass.AuxData> auxData_;
      private com.google.protobuf.MapField<java.lang.String, proto.AuxDataOuterClass.AuxData>
      internalGetAuxData() {
        if (auxData_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AuxDataDefaultEntryHolder.defaultEntry);
        }
        return auxData_;
      }
      private com.google.protobuf.MapField<java.lang.String, proto.AuxDataOuterClass.AuxData>
      internalGetMutableAuxData() {
        onChanged();;
        if (auxData_ == null) {
          auxData_ = com.google.protobuf.MapField.newMapField(
              AuxDataDefaultEntryHolder.defaultEntry);
        }
        if (!auxData_.isMutable()) {
          auxData_ = auxData_.copy();
        }
        return auxData_;
      }

      public int getAuxDataCount() {
        return internalGetAuxData().getMap().size();
      }
      /**
       * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
       */

      public boolean containsAuxData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAuxData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAuxDataMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData> getAuxData() {
        return getAuxDataMap();
      }
      /**
       * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
       */

      public java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData> getAuxDataMap() {
        return internalGetAuxData().getMap();
      }
      /**
       * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
       */

      public proto.AuxDataOuterClass.AuxData getAuxDataOrDefault(
          java.lang.String key,
          proto.AuxDataOuterClass.AuxData defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData> map =
            internalGetAuxData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
       */

      public proto.AuxDataOuterClass.AuxData getAuxDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData> map =
            internalGetAuxData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAuxData() {
        getMutableAuxData().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
       */

      public Builder removeAuxData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableAuxData().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData>
      getMutableAuxData() {
        return internalGetMutableAuxData().getMutableMap();
      }
      /**
       * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
       */
      public Builder putAuxData(
          java.lang.String key,
          proto.AuxDataOuterClass.AuxData value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableAuxData().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .proto.AuxData&gt; aux_data = 1;</code>
       */

      public Builder putAllAuxData(
          java.util.Map<java.lang.String, proto.AuxDataOuterClass.AuxData> values) {
        getMutableAuxData().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.AuxDataContainer)
    }

    // @@protoc_insertion_point(class_scope:proto.AuxDataContainer)
    private static final proto.AuxDataContainerOuterClass.AuxDataContainer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.AuxDataContainerOuterClass.AuxDataContainer();
    }

    public static proto.AuxDataContainerOuterClass.AuxDataContainer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuxDataContainer>
        PARSER = new com.google.protobuf.AbstractParser<AuxDataContainer>() {
      public AuxDataContainer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AuxDataContainer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuxDataContainer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuxDataContainer> getParserForType() {
      return PARSER;
    }

    public proto.AuxDataContainerOuterClass.AuxDataContainer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AuxDataContainer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AuxDataContainer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AuxDataContainer_AuxDataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AuxDataContainer_AuxDataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026AuxDataContainer.proto\022\005proto\032\rAuxData" +
      ".proto\"\212\001\n\020AuxDataContainer\0226\n\010aux_data\030" +
      "\001 \003(\0132$.proto.AuxDataContainer.AuxDataEn" +
      "try\032>\n\014AuxDataEntry\022\013\n\003key\030\001 \001(\t\022\035\n\005valu" +
      "e\030\002 \001(\0132\016.proto.AuxData:\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.AuxDataOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_AuxDataContainer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_AuxDataContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AuxDataContainer_descriptor,
        new java.lang.String[] { "AuxData", });
    internal_static_proto_AuxDataContainer_AuxDataEntry_descriptor =
      internal_static_proto_AuxDataContainer_descriptor.getNestedTypes().get(0);
    internal_static_proto_AuxDataContainer_AuxDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AuxDataContainer_AuxDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    proto.AuxDataOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
