// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CFG.proto

package proto;

public final class CFGOuterClass {
  private CFGOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.EdgeType}
   */
  public enum EdgeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Type_Branch = 0;</code>
     */
    Type_Branch(0),
    /**
     * <code>Type_Call = 1;</code>
     */
    Type_Call(1),
    /**
     * <code>Type_Fallthrough = 2;</code>
     */
    Type_Fallthrough(2),
    /**
     * <code>Type_Return = 3;</code>
     */
    Type_Return(3),
    /**
     * <code>Type_Syscall = 4;</code>
     */
    Type_Syscall(4),
    /**
     * <code>Type_Sysret = 5;</code>
     */
    Type_Sysret(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Type_Branch = 0;</code>
     */
    public static final int Type_Branch_VALUE = 0;
    /**
     * <code>Type_Call = 1;</code>
     */
    public static final int Type_Call_VALUE = 1;
    /**
     * <code>Type_Fallthrough = 2;</code>
     */
    public static final int Type_Fallthrough_VALUE = 2;
    /**
     * <code>Type_Return = 3;</code>
     */
    public static final int Type_Return_VALUE = 3;
    /**
     * <code>Type_Syscall = 4;</code>
     */
    public static final int Type_Syscall_VALUE = 4;
    /**
     * <code>Type_Sysret = 5;</code>
     */
    public static final int Type_Sysret_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EdgeType valueOf(int value) {
      return forNumber(value);
    }

    public static EdgeType forNumber(int value) {
      switch (value) {
        case 0: return Type_Branch;
        case 1: return Type_Call;
        case 2: return Type_Fallthrough;
        case 3: return Type_Return;
        case 4: return Type_Syscall;
        case 5: return Type_Sysret;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EdgeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EdgeType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EdgeType>() {
            public EdgeType findValueByNumber(int number) {
              return EdgeType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.CFGOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final EdgeType[] VALUES = values();

    public static EdgeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EdgeType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.EdgeType)
  }

  public interface EdgeLabelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.EdgeLabel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool conditional = 1;</code>
     */
    boolean getConditional();

    /**
     * <code>optional bool direct = 2;</code>
     */
    boolean getDirect();

    /**
     * <code>optional .proto.EdgeType type = 3;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .proto.EdgeType type = 3;</code>
     */
    proto.CFGOuterClass.EdgeType getType();
  }
  /**
   * Protobuf type {@code proto.EdgeLabel}
   */
  public  static final class EdgeLabel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.EdgeLabel)
      EdgeLabelOrBuilder {
    // Use EdgeLabel.newBuilder() to construct.
    private EdgeLabel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EdgeLabel() {
      conditional_ = false;
      direct_ = false;
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EdgeLabel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              conditional_ = input.readBool();
              break;
            }
            case 16: {

              direct_ = input.readBool();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.CFGOuterClass.internal_static_proto_EdgeLabel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.CFGOuterClass.internal_static_proto_EdgeLabel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.CFGOuterClass.EdgeLabel.class, proto.CFGOuterClass.EdgeLabel.Builder.class);
    }

    public static final int CONDITIONAL_FIELD_NUMBER = 1;
    private boolean conditional_;
    /**
     * <code>optional bool conditional = 1;</code>
     */
    public boolean getConditional() {
      return conditional_;
    }

    public static final int DIRECT_FIELD_NUMBER = 2;
    private boolean direct_;
    /**
     * <code>optional bool direct = 2;</code>
     */
    public boolean getDirect() {
      return direct_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional .proto.EdgeType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .proto.EdgeType type = 3;</code>
     */
    public proto.CFGOuterClass.EdgeType getType() {
      proto.CFGOuterClass.EdgeType result = proto.CFGOuterClass.EdgeType.valueOf(type_);
      return result == null ? proto.CFGOuterClass.EdgeType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (conditional_ != false) {
        output.writeBool(1, conditional_);
      }
      if (direct_ != false) {
        output.writeBool(2, direct_);
      }
      if (type_ != proto.CFGOuterClass.EdgeType.Type_Branch.getNumber()) {
        output.writeEnum(3, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (conditional_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, conditional_);
      }
      if (direct_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, direct_);
      }
      if (type_ != proto.CFGOuterClass.EdgeType.Type_Branch.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.CFGOuterClass.EdgeLabel)) {
        return super.equals(obj);
      }
      proto.CFGOuterClass.EdgeLabel other = (proto.CFGOuterClass.EdgeLabel) obj;

      boolean result = true;
      result = result && (getConditional()
          == other.getConditional());
      result = result && (getDirect()
          == other.getDirect());
      result = result && type_ == other.type_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CONDITIONAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getConditional());
      hash = (37 * hash) + DIRECT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDirect());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.CFGOuterClass.EdgeLabel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.CFGOuterClass.EdgeLabel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.CFGOuterClass.EdgeLabel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.CFGOuterClass.EdgeLabel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.CFGOuterClass.EdgeLabel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.CFGOuterClass.EdgeLabel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.CFGOuterClass.EdgeLabel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.CFGOuterClass.EdgeLabel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.CFGOuterClass.EdgeLabel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.CFGOuterClass.EdgeLabel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.CFGOuterClass.EdgeLabel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.EdgeLabel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.EdgeLabel)
        proto.CFGOuterClass.EdgeLabelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.CFGOuterClass.internal_static_proto_EdgeLabel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.CFGOuterClass.internal_static_proto_EdgeLabel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.CFGOuterClass.EdgeLabel.class, proto.CFGOuterClass.EdgeLabel.Builder.class);
      }

      // Construct using proto.CFGOuterClass.EdgeLabel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        conditional_ = false;

        direct_ = false;

        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.CFGOuterClass.internal_static_proto_EdgeLabel_descriptor;
      }

      public proto.CFGOuterClass.EdgeLabel getDefaultInstanceForType() {
        return proto.CFGOuterClass.EdgeLabel.getDefaultInstance();
      }

      public proto.CFGOuterClass.EdgeLabel build() {
        proto.CFGOuterClass.EdgeLabel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.CFGOuterClass.EdgeLabel buildPartial() {
        proto.CFGOuterClass.EdgeLabel result = new proto.CFGOuterClass.EdgeLabel(this);
        result.conditional_ = conditional_;
        result.direct_ = direct_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.CFGOuterClass.EdgeLabel) {
          return mergeFrom((proto.CFGOuterClass.EdgeLabel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.CFGOuterClass.EdgeLabel other) {
        if (other == proto.CFGOuterClass.EdgeLabel.getDefaultInstance()) return this;
        if (other.getConditional() != false) {
          setConditional(other.getConditional());
        }
        if (other.getDirect() != false) {
          setDirect(other.getDirect());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.CFGOuterClass.EdgeLabel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.CFGOuterClass.EdgeLabel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean conditional_ ;
      /**
       * <code>optional bool conditional = 1;</code>
       */
      public boolean getConditional() {
        return conditional_;
      }
      /**
       * <code>optional bool conditional = 1;</code>
       */
      public Builder setConditional(boolean value) {
        
        conditional_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool conditional = 1;</code>
       */
      public Builder clearConditional() {
        
        conditional_ = false;
        onChanged();
        return this;
      }

      private boolean direct_ ;
      /**
       * <code>optional bool direct = 2;</code>
       */
      public boolean getDirect() {
        return direct_;
      }
      /**
       * <code>optional bool direct = 2;</code>
       */
      public Builder setDirect(boolean value) {
        
        direct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool direct = 2;</code>
       */
      public Builder clearDirect() {
        
        direct_ = false;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .proto.EdgeType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .proto.EdgeType type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.EdgeType type = 3;</code>
       */
      public proto.CFGOuterClass.EdgeType getType() {
        proto.CFGOuterClass.EdgeType result = proto.CFGOuterClass.EdgeType.valueOf(type_);
        return result == null ? proto.CFGOuterClass.EdgeType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .proto.EdgeType type = 3;</code>
       */
      public Builder setType(proto.CFGOuterClass.EdgeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.EdgeType type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.EdgeLabel)
    }

    // @@protoc_insertion_point(class_scope:proto.EdgeLabel)
    private static final proto.CFGOuterClass.EdgeLabel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.CFGOuterClass.EdgeLabel();
    }

    public static proto.CFGOuterClass.EdgeLabel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EdgeLabel>
        PARSER = new com.google.protobuf.AbstractParser<EdgeLabel>() {
      public EdgeLabel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EdgeLabel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EdgeLabel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EdgeLabel> getParserForType() {
      return PARSER;
    }

    public proto.CFGOuterClass.EdgeLabel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EdgeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Edge)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes source_uuid = 1;</code>
     */
    com.google.protobuf.ByteString getSourceUuid();

    /**
     * <code>optional bytes target_uuid = 2;</code>
     */
    com.google.protobuf.ByteString getTargetUuid();

    /**
     * <code>optional .proto.EdgeLabel label = 5;</code>
     */
    boolean hasLabel();
    /**
     * <code>optional .proto.EdgeLabel label = 5;</code>
     */
    proto.CFGOuterClass.EdgeLabel getLabel();
    /**
     * <code>optional .proto.EdgeLabel label = 5;</code>
     */
    proto.CFGOuterClass.EdgeLabelOrBuilder getLabelOrBuilder();
  }
  /**
   * Protobuf type {@code proto.Edge}
   */
  public  static final class Edge extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Edge)
      EdgeOrBuilder {
    // Use Edge.newBuilder() to construct.
    private Edge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Edge() {
      sourceUuid_ = com.google.protobuf.ByteString.EMPTY;
      targetUuid_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Edge(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              sourceUuid_ = input.readBytes();
              break;
            }
            case 18: {

              targetUuid_ = input.readBytes();
              break;
            }
            case 42: {
              proto.CFGOuterClass.EdgeLabel.Builder subBuilder = null;
              if (label_ != null) {
                subBuilder = label_.toBuilder();
              }
              label_ = input.readMessage(proto.CFGOuterClass.EdgeLabel.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(label_);
                label_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.CFGOuterClass.internal_static_proto_Edge_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.CFGOuterClass.internal_static_proto_Edge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.CFGOuterClass.Edge.class, proto.CFGOuterClass.Edge.Builder.class);
    }

    public static final int SOURCE_UUID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString sourceUuid_;
    /**
     * <code>optional bytes source_uuid = 1;</code>
     */
    public com.google.protobuf.ByteString getSourceUuid() {
      return sourceUuid_;
    }

    public static final int TARGET_UUID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString targetUuid_;
    /**
     * <code>optional bytes target_uuid = 2;</code>
     */
    public com.google.protobuf.ByteString getTargetUuid() {
      return targetUuid_;
    }

    public static final int LABEL_FIELD_NUMBER = 5;
    private proto.CFGOuterClass.EdgeLabel label_;
    /**
     * <code>optional .proto.EdgeLabel label = 5;</code>
     */
    public boolean hasLabel() {
      return label_ != null;
    }
    /**
     * <code>optional .proto.EdgeLabel label = 5;</code>
     */
    public proto.CFGOuterClass.EdgeLabel getLabel() {
      return label_ == null ? proto.CFGOuterClass.EdgeLabel.getDefaultInstance() : label_;
    }
    /**
     * <code>optional .proto.EdgeLabel label = 5;</code>
     */
    public proto.CFGOuterClass.EdgeLabelOrBuilder getLabelOrBuilder() {
      return getLabel();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!sourceUuid_.isEmpty()) {
        output.writeBytes(1, sourceUuid_);
      }
      if (!targetUuid_.isEmpty()) {
        output.writeBytes(2, targetUuid_);
      }
      if (label_ != null) {
        output.writeMessage(5, getLabel());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!sourceUuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, sourceUuid_);
      }
      if (!targetUuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, targetUuid_);
      }
      if (label_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getLabel());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.CFGOuterClass.Edge)) {
        return super.equals(obj);
      }
      proto.CFGOuterClass.Edge other = (proto.CFGOuterClass.Edge) obj;

      boolean result = true;
      result = result && getSourceUuid()
          .equals(other.getSourceUuid());
      result = result && getTargetUuid()
          .equals(other.getTargetUuid());
      result = result && (hasLabel() == other.hasLabel());
      if (hasLabel()) {
        result = result && getLabel()
            .equals(other.getLabel());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SOURCE_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getSourceUuid().hashCode();
      hash = (37 * hash) + TARGET_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetUuid().hashCode();
      if (hasLabel()) {
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabel().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.CFGOuterClass.Edge parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.CFGOuterClass.Edge parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.CFGOuterClass.Edge parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.CFGOuterClass.Edge parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.CFGOuterClass.Edge parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.CFGOuterClass.Edge parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.CFGOuterClass.Edge parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.CFGOuterClass.Edge parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.CFGOuterClass.Edge parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.CFGOuterClass.Edge parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.CFGOuterClass.Edge prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Edge}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Edge)
        proto.CFGOuterClass.EdgeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.CFGOuterClass.internal_static_proto_Edge_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.CFGOuterClass.internal_static_proto_Edge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.CFGOuterClass.Edge.class, proto.CFGOuterClass.Edge.Builder.class);
      }

      // Construct using proto.CFGOuterClass.Edge.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sourceUuid_ = com.google.protobuf.ByteString.EMPTY;

        targetUuid_ = com.google.protobuf.ByteString.EMPTY;

        if (labelBuilder_ == null) {
          label_ = null;
        } else {
          label_ = null;
          labelBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.CFGOuterClass.internal_static_proto_Edge_descriptor;
      }

      public proto.CFGOuterClass.Edge getDefaultInstanceForType() {
        return proto.CFGOuterClass.Edge.getDefaultInstance();
      }

      public proto.CFGOuterClass.Edge build() {
        proto.CFGOuterClass.Edge result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.CFGOuterClass.Edge buildPartial() {
        proto.CFGOuterClass.Edge result = new proto.CFGOuterClass.Edge(this);
        result.sourceUuid_ = sourceUuid_;
        result.targetUuid_ = targetUuid_;
        if (labelBuilder_ == null) {
          result.label_ = label_;
        } else {
          result.label_ = labelBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.CFGOuterClass.Edge) {
          return mergeFrom((proto.CFGOuterClass.Edge)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.CFGOuterClass.Edge other) {
        if (other == proto.CFGOuterClass.Edge.getDefaultInstance()) return this;
        if (other.getSourceUuid() != com.google.protobuf.ByteString.EMPTY) {
          setSourceUuid(other.getSourceUuid());
        }
        if (other.getTargetUuid() != com.google.protobuf.ByteString.EMPTY) {
          setTargetUuid(other.getTargetUuid());
        }
        if (other.hasLabel()) {
          mergeLabel(other.getLabel());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.CFGOuterClass.Edge parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.CFGOuterClass.Edge) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString sourceUuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes source_uuid = 1;</code>
       */
      public com.google.protobuf.ByteString getSourceUuid() {
        return sourceUuid_;
      }
      /**
       * <code>optional bytes source_uuid = 1;</code>
       */
      public Builder setSourceUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sourceUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes source_uuid = 1;</code>
       */
      public Builder clearSourceUuid() {
        
        sourceUuid_ = getDefaultInstance().getSourceUuid();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString targetUuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes target_uuid = 2;</code>
       */
      public com.google.protobuf.ByteString getTargetUuid() {
        return targetUuid_;
      }
      /**
       * <code>optional bytes target_uuid = 2;</code>
       */
      public Builder setTargetUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        targetUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes target_uuid = 2;</code>
       */
      public Builder clearTargetUuid() {
        
        targetUuid_ = getDefaultInstance().getTargetUuid();
        onChanged();
        return this;
      }

      private proto.CFGOuterClass.EdgeLabel label_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.CFGOuterClass.EdgeLabel, proto.CFGOuterClass.EdgeLabel.Builder, proto.CFGOuterClass.EdgeLabelOrBuilder> labelBuilder_;
      /**
       * <code>optional .proto.EdgeLabel label = 5;</code>
       */
      public boolean hasLabel() {
        return labelBuilder_ != null || label_ != null;
      }
      /**
       * <code>optional .proto.EdgeLabel label = 5;</code>
       */
      public proto.CFGOuterClass.EdgeLabel getLabel() {
        if (labelBuilder_ == null) {
          return label_ == null ? proto.CFGOuterClass.EdgeLabel.getDefaultInstance() : label_;
        } else {
          return labelBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.EdgeLabel label = 5;</code>
       */
      public Builder setLabel(proto.CFGOuterClass.EdgeLabel value) {
        if (labelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          label_ = value;
          onChanged();
        } else {
          labelBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.EdgeLabel label = 5;</code>
       */
      public Builder setLabel(
          proto.CFGOuterClass.EdgeLabel.Builder builderForValue) {
        if (labelBuilder_ == null) {
          label_ = builderForValue.build();
          onChanged();
        } else {
          labelBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.EdgeLabel label = 5;</code>
       */
      public Builder mergeLabel(proto.CFGOuterClass.EdgeLabel value) {
        if (labelBuilder_ == null) {
          if (label_ != null) {
            label_ =
              proto.CFGOuterClass.EdgeLabel.newBuilder(label_).mergeFrom(value).buildPartial();
          } else {
            label_ = value;
          }
          onChanged();
        } else {
          labelBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.EdgeLabel label = 5;</code>
       */
      public Builder clearLabel() {
        if (labelBuilder_ == null) {
          label_ = null;
          onChanged();
        } else {
          label_ = null;
          labelBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.EdgeLabel label = 5;</code>
       */
      public proto.CFGOuterClass.EdgeLabel.Builder getLabelBuilder() {
        
        onChanged();
        return getLabelFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.EdgeLabel label = 5;</code>
       */
      public proto.CFGOuterClass.EdgeLabelOrBuilder getLabelOrBuilder() {
        if (labelBuilder_ != null) {
          return labelBuilder_.getMessageOrBuilder();
        } else {
          return label_ == null ?
              proto.CFGOuterClass.EdgeLabel.getDefaultInstance() : label_;
        }
      }
      /**
       * <code>optional .proto.EdgeLabel label = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.CFGOuterClass.EdgeLabel, proto.CFGOuterClass.EdgeLabel.Builder, proto.CFGOuterClass.EdgeLabelOrBuilder> 
          getLabelFieldBuilder() {
        if (labelBuilder_ == null) {
          labelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.CFGOuterClass.EdgeLabel, proto.CFGOuterClass.EdgeLabel.Builder, proto.CFGOuterClass.EdgeLabelOrBuilder>(
                  getLabel(),
                  getParentForChildren(),
                  isClean());
          label_ = null;
        }
        return labelBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Edge)
    }

    // @@protoc_insertion_point(class_scope:proto.Edge)
    private static final proto.CFGOuterClass.Edge DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.CFGOuterClass.Edge();
    }

    public static proto.CFGOuterClass.Edge getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Edge>
        PARSER = new com.google.protobuf.AbstractParser<Edge>() {
      public Edge parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Edge(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Edge> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Edge> getParserForType() {
      return PARSER;
    }

    public proto.CFGOuterClass.Edge getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CFGOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.CFG)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes vertices = 3;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getVerticesList();
    /**
     * <code>repeated bytes vertices = 3;</code>
     */
    int getVerticesCount();
    /**
     * <code>repeated bytes vertices = 3;</code>
     */
    com.google.protobuf.ByteString getVertices(int index);

    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    java.util.List<proto.CFGOuterClass.Edge> 
        getEdgesList();
    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    proto.CFGOuterClass.Edge getEdges(int index);
    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    int getEdgesCount();
    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    java.util.List<? extends proto.CFGOuterClass.EdgeOrBuilder> 
        getEdgesOrBuilderList();
    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    proto.CFGOuterClass.EdgeOrBuilder getEdgesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.CFG}
   */
  public  static final class CFG extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.CFG)
      CFGOrBuilder {
    // Use CFG.newBuilder() to construct.
    private CFG(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CFG() {
      vertices_ = java.util.Collections.emptyList();
      edges_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CFG(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                edges_ = new java.util.ArrayList<proto.CFGOuterClass.Edge>();
                mutable_bitField0_ |= 0x00000002;
              }
              edges_.add(
                  input.readMessage(proto.CFGOuterClass.Edge.parser(), extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                vertices_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              vertices_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          edges_ = java.util.Collections.unmodifiableList(edges_);
        }
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          vertices_ = java.util.Collections.unmodifiableList(vertices_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.CFGOuterClass.internal_static_proto_CFG_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.CFGOuterClass.internal_static_proto_CFG_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.CFGOuterClass.CFG.class, proto.CFGOuterClass.CFG.Builder.class);
    }

    public static final int VERTICES_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> vertices_;
    /**
     * <code>repeated bytes vertices = 3;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getVerticesList() {
      return vertices_;
    }
    /**
     * <code>repeated bytes vertices = 3;</code>
     */
    public int getVerticesCount() {
      return vertices_.size();
    }
    /**
     * <code>repeated bytes vertices = 3;</code>
     */
    public com.google.protobuf.ByteString getVertices(int index) {
      return vertices_.get(index);
    }

    public static final int EDGES_FIELD_NUMBER = 2;
    private java.util.List<proto.CFGOuterClass.Edge> edges_;
    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    public java.util.List<proto.CFGOuterClass.Edge> getEdgesList() {
      return edges_;
    }
    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    public java.util.List<? extends proto.CFGOuterClass.EdgeOrBuilder> 
        getEdgesOrBuilderList() {
      return edges_;
    }
    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    public int getEdgesCount() {
      return edges_.size();
    }
    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    public proto.CFGOuterClass.Edge getEdges(int index) {
      return edges_.get(index);
    }
    /**
     * <code>repeated .proto.Edge edges = 2;</code>
     */
    public proto.CFGOuterClass.EdgeOrBuilder getEdgesOrBuilder(
        int index) {
      return edges_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < edges_.size(); i++) {
        output.writeMessage(2, edges_.get(i));
      }
      for (int i = 0; i < vertices_.size(); i++) {
        output.writeBytes(3, vertices_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < edges_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, edges_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < vertices_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(vertices_.get(i));
        }
        size += dataSize;
        size += 1 * getVerticesList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.CFGOuterClass.CFG)) {
        return super.equals(obj);
      }
      proto.CFGOuterClass.CFG other = (proto.CFGOuterClass.CFG) obj;

      boolean result = true;
      result = result && getVerticesList()
          .equals(other.getVerticesList());
      result = result && getEdgesList()
          .equals(other.getEdgesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getVerticesCount() > 0) {
        hash = (37 * hash) + VERTICES_FIELD_NUMBER;
        hash = (53 * hash) + getVerticesList().hashCode();
      }
      if (getEdgesCount() > 0) {
        hash = (37 * hash) + EDGES_FIELD_NUMBER;
        hash = (53 * hash) + getEdgesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.CFGOuterClass.CFG parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.CFGOuterClass.CFG parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.CFGOuterClass.CFG parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.CFGOuterClass.CFG parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.CFGOuterClass.CFG parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.CFGOuterClass.CFG parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.CFGOuterClass.CFG parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.CFGOuterClass.CFG parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.CFGOuterClass.CFG parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.CFGOuterClass.CFG parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.CFGOuterClass.CFG prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.CFG}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.CFG)
        proto.CFGOuterClass.CFGOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.CFGOuterClass.internal_static_proto_CFG_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.CFGOuterClass.internal_static_proto_CFG_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.CFGOuterClass.CFG.class, proto.CFGOuterClass.CFG.Builder.class);
      }

      // Construct using proto.CFGOuterClass.CFG.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEdgesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        vertices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (edgesBuilder_ == null) {
          edges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          edgesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.CFGOuterClass.internal_static_proto_CFG_descriptor;
      }

      public proto.CFGOuterClass.CFG getDefaultInstanceForType() {
        return proto.CFGOuterClass.CFG.getDefaultInstance();
      }

      public proto.CFGOuterClass.CFG build() {
        proto.CFGOuterClass.CFG result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.CFGOuterClass.CFG buildPartial() {
        proto.CFGOuterClass.CFG result = new proto.CFGOuterClass.CFG(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          vertices_ = java.util.Collections.unmodifiableList(vertices_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vertices_ = vertices_;
        if (edgesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            edges_ = java.util.Collections.unmodifiableList(edges_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.edges_ = edges_;
        } else {
          result.edges_ = edgesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.CFGOuterClass.CFG) {
          return mergeFrom((proto.CFGOuterClass.CFG)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.CFGOuterClass.CFG other) {
        if (other == proto.CFGOuterClass.CFG.getDefaultInstance()) return this;
        if (!other.vertices_.isEmpty()) {
          if (vertices_.isEmpty()) {
            vertices_ = other.vertices_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVerticesIsMutable();
            vertices_.addAll(other.vertices_);
          }
          onChanged();
        }
        if (edgesBuilder_ == null) {
          if (!other.edges_.isEmpty()) {
            if (edges_.isEmpty()) {
              edges_ = other.edges_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEdgesIsMutable();
              edges_.addAll(other.edges_);
            }
            onChanged();
          }
        } else {
          if (!other.edges_.isEmpty()) {
            if (edgesBuilder_.isEmpty()) {
              edgesBuilder_.dispose();
              edgesBuilder_ = null;
              edges_ = other.edges_;
              bitField0_ = (bitField0_ & ~0x00000002);
              edgesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEdgesFieldBuilder() : null;
            } else {
              edgesBuilder_.addAllMessages(other.edges_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.CFGOuterClass.CFG parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.CFGOuterClass.CFG) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> vertices_ = java.util.Collections.emptyList();
      private void ensureVerticesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          vertices_ = new java.util.ArrayList<com.google.protobuf.ByteString>(vertices_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes vertices = 3;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getVerticesList() {
        return java.util.Collections.unmodifiableList(vertices_);
      }
      /**
       * <code>repeated bytes vertices = 3;</code>
       */
      public int getVerticesCount() {
        return vertices_.size();
      }
      /**
       * <code>repeated bytes vertices = 3;</code>
       */
      public com.google.protobuf.ByteString getVertices(int index) {
        return vertices_.get(index);
      }
      /**
       * <code>repeated bytes vertices = 3;</code>
       */
      public Builder setVertices(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVerticesIsMutable();
        vertices_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes vertices = 3;</code>
       */
      public Builder addVertices(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVerticesIsMutable();
        vertices_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes vertices = 3;</code>
       */
      public Builder addAllVertices(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureVerticesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vertices_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes vertices = 3;</code>
       */
      public Builder clearVertices() {
        vertices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<proto.CFGOuterClass.Edge> edges_ =
        java.util.Collections.emptyList();
      private void ensureEdgesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          edges_ = new java.util.ArrayList<proto.CFGOuterClass.Edge>(edges_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.CFGOuterClass.Edge, proto.CFGOuterClass.Edge.Builder, proto.CFGOuterClass.EdgeOrBuilder> edgesBuilder_;

      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public java.util.List<proto.CFGOuterClass.Edge> getEdgesList() {
        if (edgesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(edges_);
        } else {
          return edgesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public int getEdgesCount() {
        if (edgesBuilder_ == null) {
          return edges_.size();
        } else {
          return edgesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public proto.CFGOuterClass.Edge getEdges(int index) {
        if (edgesBuilder_ == null) {
          return edges_.get(index);
        } else {
          return edgesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public Builder setEdges(
          int index, proto.CFGOuterClass.Edge value) {
        if (edgesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgesIsMutable();
          edges_.set(index, value);
          onChanged();
        } else {
          edgesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public Builder setEdges(
          int index, proto.CFGOuterClass.Edge.Builder builderForValue) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.set(index, builderForValue.build());
          onChanged();
        } else {
          edgesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public Builder addEdges(proto.CFGOuterClass.Edge value) {
        if (edgesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgesIsMutable();
          edges_.add(value);
          onChanged();
        } else {
          edgesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public Builder addEdges(
          int index, proto.CFGOuterClass.Edge value) {
        if (edgesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgesIsMutable();
          edges_.add(index, value);
          onChanged();
        } else {
          edgesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public Builder addEdges(
          proto.CFGOuterClass.Edge.Builder builderForValue) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.add(builderForValue.build());
          onChanged();
        } else {
          edgesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public Builder addEdges(
          int index, proto.CFGOuterClass.Edge.Builder builderForValue) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.add(index, builderForValue.build());
          onChanged();
        } else {
          edgesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public Builder addAllEdges(
          java.lang.Iterable<? extends proto.CFGOuterClass.Edge> values) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, edges_);
          onChanged();
        } else {
          edgesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public Builder clearEdges() {
        if (edgesBuilder_ == null) {
          edges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          edgesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public Builder removeEdges(int index) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.remove(index);
          onChanged();
        } else {
          edgesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public proto.CFGOuterClass.Edge.Builder getEdgesBuilder(
          int index) {
        return getEdgesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public proto.CFGOuterClass.EdgeOrBuilder getEdgesOrBuilder(
          int index) {
        if (edgesBuilder_ == null) {
          return edges_.get(index);  } else {
          return edgesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public java.util.List<? extends proto.CFGOuterClass.EdgeOrBuilder> 
           getEdgesOrBuilderList() {
        if (edgesBuilder_ != null) {
          return edgesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(edges_);
        }
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public proto.CFGOuterClass.Edge.Builder addEdgesBuilder() {
        return getEdgesFieldBuilder().addBuilder(
            proto.CFGOuterClass.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public proto.CFGOuterClass.Edge.Builder addEdgesBuilder(
          int index) {
        return getEdgesFieldBuilder().addBuilder(
            index, proto.CFGOuterClass.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Edge edges = 2;</code>
       */
      public java.util.List<proto.CFGOuterClass.Edge.Builder> 
           getEdgesBuilderList() {
        return getEdgesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.CFGOuterClass.Edge, proto.CFGOuterClass.Edge.Builder, proto.CFGOuterClass.EdgeOrBuilder> 
          getEdgesFieldBuilder() {
        if (edgesBuilder_ == null) {
          edgesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.CFGOuterClass.Edge, proto.CFGOuterClass.Edge.Builder, proto.CFGOuterClass.EdgeOrBuilder>(
                  edges_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          edges_ = null;
        }
        return edgesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.CFG)
    }

    // @@protoc_insertion_point(class_scope:proto.CFG)
    private static final proto.CFGOuterClass.CFG DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.CFGOuterClass.CFG();
    }

    public static proto.CFGOuterClass.CFG getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CFG>
        PARSER = new com.google.protobuf.AbstractParser<CFG>() {
      public CFG parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CFG(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CFG> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CFG> getParserForType() {
      return PARSER;
    }

    public proto.CFGOuterClass.CFG getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EdgeLabel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EdgeLabel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Edge_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Edge_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CFG_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CFG_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCFG.proto\022\005proto\032\013Block.proto\"O\n\tEdgeL" +
      "abel\022\023\n\013conditional\030\001 \001(\010\022\016\n\006direct\030\002 \001(" +
      "\010\022\035\n\004type\030\003 \001(\0162\017.proto.EdgeType\"o\n\004Edge" +
      "\022\023\n\013source_uuid\030\001 \001(\014\022\023\n\013target_uuid\030\002 \001" +
      "(\014\022\037\n\005label\030\005 \001(\0132\020.proto.EdgeLabelJ\004\010\003\020" +
      "\004J\004\010\004\020\005R\007booleanR\007integer\"A\n\003CFG\022\020\n\010vert" +
      "ices\030\003 \003(\014\022\032\n\005edges\030\002 \003(\0132\013.proto.EdgeJ\004" +
      "\010\001\020\002R\006blocks*t\n\010EdgeType\022\017\n\013Type_Branch\020" +
      "\000\022\r\n\tType_Call\020\001\022\024\n\020Type_Fallthrough\020\002\022\017" +
      "\n\013Type_Return\020\003\022\020\n\014Type_Syscall\020\004\022\017\n\013Typ",
      "e_Sysret\020\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.BlockOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_EdgeLabel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_EdgeLabel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EdgeLabel_descriptor,
        new java.lang.String[] { "Conditional", "Direct", "Type", });
    internal_static_proto_Edge_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Edge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Edge_descriptor,
        new java.lang.String[] { "SourceUuid", "TargetUuid", "Label", });
    internal_static_proto_CFG_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_CFG_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CFG_descriptor,
        new java.lang.String[] { "Vertices", "Edges", });
    proto.BlockOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
