// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SymbolicExpression.proto

package proto;

public final class SymbolicExpressionOuterClass {
  private SymbolicExpressionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SymStackConstOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SymStackConst)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 offset = 1;</code>
     */
    int getOffset();

    /**
     * <code>optional bytes symbol_uuid = 2;</code>
     */
    com.google.protobuf.ByteString getSymbolUuid();
  }
  /**
   * Protobuf type {@code proto.SymStackConst}
   */
  public  static final class SymStackConst extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SymStackConst)
      SymStackConstOrBuilder {
    // Use SymStackConst.newBuilder() to construct.
    private SymStackConst(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SymStackConst() {
      offset_ = 0;
      symbolUuid_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SymStackConst(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              offset_ = input.readInt32();
              break;
            }
            case 18: {

              symbolUuid_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SymbolicExpressionOuterClass.internal_static_proto_SymStackConst_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SymbolicExpressionOuterClass.internal_static_proto_SymStackConst_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SymbolicExpressionOuterClass.SymStackConst.class, proto.SymbolicExpressionOuterClass.SymStackConst.Builder.class);
    }

    public static final int OFFSET_FIELD_NUMBER = 1;
    private int offset_;
    /**
     * <code>optional int32 offset = 1;</code>
     */
    public int getOffset() {
      return offset_;
    }

    public static final int SYMBOL_UUID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString symbolUuid_;
    /**
     * <code>optional bytes symbol_uuid = 2;</code>
     */
    public com.google.protobuf.ByteString getSymbolUuid() {
      return symbolUuid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (offset_ != 0) {
        output.writeInt32(1, offset_);
      }
      if (!symbolUuid_.isEmpty()) {
        output.writeBytes(2, symbolUuid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, offset_);
      }
      if (!symbolUuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, symbolUuid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.SymbolicExpressionOuterClass.SymStackConst)) {
        return super.equals(obj);
      }
      proto.SymbolicExpressionOuterClass.SymStackConst other = (proto.SymbolicExpressionOuterClass.SymStackConst) obj;

      boolean result = true;
      result = result && (getOffset()
          == other.getOffset());
      result = result && getSymbolUuid()
          .equals(other.getSymbolUuid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset();
      hash = (37 * hash) + SYMBOL_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getSymbolUuid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.SymbolicExpressionOuterClass.SymStackConst parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolicExpressionOuterClass.SymStackConst parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymStackConst parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolicExpressionOuterClass.SymStackConst parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymStackConst parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymStackConst parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymStackConst parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymStackConst parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymStackConst parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymStackConst parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.SymbolicExpressionOuterClass.SymStackConst prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SymStackConst}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SymStackConst)
        proto.SymbolicExpressionOuterClass.SymStackConstOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymStackConst_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymStackConst_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SymbolicExpressionOuterClass.SymStackConst.class, proto.SymbolicExpressionOuterClass.SymStackConst.Builder.class);
      }

      // Construct using proto.SymbolicExpressionOuterClass.SymStackConst.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        offset_ = 0;

        symbolUuid_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymStackConst_descriptor;
      }

      public proto.SymbolicExpressionOuterClass.SymStackConst getDefaultInstanceForType() {
        return proto.SymbolicExpressionOuterClass.SymStackConst.getDefaultInstance();
      }

      public proto.SymbolicExpressionOuterClass.SymStackConst build() {
        proto.SymbolicExpressionOuterClass.SymStackConst result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SymbolicExpressionOuterClass.SymStackConst buildPartial() {
        proto.SymbolicExpressionOuterClass.SymStackConst result = new proto.SymbolicExpressionOuterClass.SymStackConst(this);
        result.offset_ = offset_;
        result.symbolUuid_ = symbolUuid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SymbolicExpressionOuterClass.SymStackConst) {
          return mergeFrom((proto.SymbolicExpressionOuterClass.SymStackConst)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SymbolicExpressionOuterClass.SymStackConst other) {
        if (other == proto.SymbolicExpressionOuterClass.SymStackConst.getDefaultInstance()) return this;
        if (other.getOffset() != 0) {
          setOffset(other.getOffset());
        }
        if (other.getSymbolUuid() != com.google.protobuf.ByteString.EMPTY) {
          setSymbolUuid(other.getSymbolUuid());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SymbolicExpressionOuterClass.SymStackConst parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SymbolicExpressionOuterClass.SymStackConst) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int offset_ ;
      /**
       * <code>optional int32 offset = 1;</code>
       */
      public int getOffset() {
        return offset_;
      }
      /**
       * <code>optional int32 offset = 1;</code>
       */
      public Builder setOffset(int value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 offset = 1;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString symbolUuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes symbol_uuid = 2;</code>
       */
      public com.google.protobuf.ByteString getSymbolUuid() {
        return symbolUuid_;
      }
      /**
       * <code>optional bytes symbol_uuid = 2;</code>
       */
      public Builder setSymbolUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbolUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes symbol_uuid = 2;</code>
       */
      public Builder clearSymbolUuid() {
        
        symbolUuid_ = getDefaultInstance().getSymbolUuid();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.SymStackConst)
    }

    // @@protoc_insertion_point(class_scope:proto.SymStackConst)
    private static final proto.SymbolicExpressionOuterClass.SymStackConst DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.SymbolicExpressionOuterClass.SymStackConst();
    }

    public static proto.SymbolicExpressionOuterClass.SymStackConst getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SymStackConst>
        PARSER = new com.google.protobuf.AbstractParser<SymStackConst>() {
      public SymStackConst parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SymStackConst(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SymStackConst> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SymStackConst> getParserForType() {
      return PARSER;
    }

    public proto.SymbolicExpressionOuterClass.SymStackConst getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SymAddrConstOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SymAddrConst)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 offset = 1;</code>
     */
    long getOffset();

    /**
     * <code>optional bytes symbol_uuid = 2;</code>
     */
    com.google.protobuf.ByteString getSymbolUuid();
  }
  /**
   * Protobuf type {@code proto.SymAddrConst}
   */
  public  static final class SymAddrConst extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SymAddrConst)
      SymAddrConstOrBuilder {
    // Use SymAddrConst.newBuilder() to construct.
    private SymAddrConst(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SymAddrConst() {
      offset_ = 0L;
      symbolUuid_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SymAddrConst(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              offset_ = input.readInt64();
              break;
            }
            case 18: {

              symbolUuid_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrConst_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrConst_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SymbolicExpressionOuterClass.SymAddrConst.class, proto.SymbolicExpressionOuterClass.SymAddrConst.Builder.class);
    }

    public static final int OFFSET_FIELD_NUMBER = 1;
    private long offset_;
    /**
     * <code>optional int64 offset = 1;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int SYMBOL_UUID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString symbolUuid_;
    /**
     * <code>optional bytes symbol_uuid = 2;</code>
     */
    public com.google.protobuf.ByteString getSymbolUuid() {
      return symbolUuid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (offset_ != 0L) {
        output.writeInt64(1, offset_);
      }
      if (!symbolUuid_.isEmpty()) {
        output.writeBytes(2, symbolUuid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, offset_);
      }
      if (!symbolUuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, symbolUuid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.SymbolicExpressionOuterClass.SymAddrConst)) {
        return super.equals(obj);
      }
      proto.SymbolicExpressionOuterClass.SymAddrConst other = (proto.SymbolicExpressionOuterClass.SymAddrConst) obj;

      boolean result = true;
      result = result && (getOffset()
          == other.getOffset());
      result = result && getSymbolUuid()
          .equals(other.getSymbolUuid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      hash = (37 * hash) + SYMBOL_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getSymbolUuid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrConst parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.SymbolicExpressionOuterClass.SymAddrConst prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SymAddrConst}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SymAddrConst)
        proto.SymbolicExpressionOuterClass.SymAddrConstOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrConst_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrConst_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SymbolicExpressionOuterClass.SymAddrConst.class, proto.SymbolicExpressionOuterClass.SymAddrConst.Builder.class);
      }

      // Construct using proto.SymbolicExpressionOuterClass.SymAddrConst.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        offset_ = 0L;

        symbolUuid_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrConst_descriptor;
      }

      public proto.SymbolicExpressionOuterClass.SymAddrConst getDefaultInstanceForType() {
        return proto.SymbolicExpressionOuterClass.SymAddrConst.getDefaultInstance();
      }

      public proto.SymbolicExpressionOuterClass.SymAddrConst build() {
        proto.SymbolicExpressionOuterClass.SymAddrConst result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SymbolicExpressionOuterClass.SymAddrConst buildPartial() {
        proto.SymbolicExpressionOuterClass.SymAddrConst result = new proto.SymbolicExpressionOuterClass.SymAddrConst(this);
        result.offset_ = offset_;
        result.symbolUuid_ = symbolUuid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SymbolicExpressionOuterClass.SymAddrConst) {
          return mergeFrom((proto.SymbolicExpressionOuterClass.SymAddrConst)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SymbolicExpressionOuterClass.SymAddrConst other) {
        if (other == proto.SymbolicExpressionOuterClass.SymAddrConst.getDefaultInstance()) return this;
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (other.getSymbolUuid() != com.google.protobuf.ByteString.EMPTY) {
          setSymbolUuid(other.getSymbolUuid());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SymbolicExpressionOuterClass.SymAddrConst parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SymbolicExpressionOuterClass.SymAddrConst) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long offset_ ;
      /**
       * <code>optional int64 offset = 1;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>optional int64 offset = 1;</code>
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 offset = 1;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString symbolUuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes symbol_uuid = 2;</code>
       */
      public com.google.protobuf.ByteString getSymbolUuid() {
        return symbolUuid_;
      }
      /**
       * <code>optional bytes symbol_uuid = 2;</code>
       */
      public Builder setSymbolUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbolUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes symbol_uuid = 2;</code>
       */
      public Builder clearSymbolUuid() {
        
        symbolUuid_ = getDefaultInstance().getSymbolUuid();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.SymAddrConst)
    }

    // @@protoc_insertion_point(class_scope:proto.SymAddrConst)
    private static final proto.SymbolicExpressionOuterClass.SymAddrConst DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.SymbolicExpressionOuterClass.SymAddrConst();
    }

    public static proto.SymbolicExpressionOuterClass.SymAddrConst getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SymAddrConst>
        PARSER = new com.google.protobuf.AbstractParser<SymAddrConst>() {
      public SymAddrConst parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SymAddrConst(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SymAddrConst> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SymAddrConst> getParserForType() {
      return PARSER;
    }

    public proto.SymbolicExpressionOuterClass.SymAddrConst getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SymAddrAddrOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SymAddrAddr)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 scale = 1;</code>
     */
    long getScale();

    /**
     * <code>optional int64 offset = 2;</code>
     */
    long getOffset();

    /**
     * <code>optional bytes symbol1_uuid = 3;</code>
     */
    com.google.protobuf.ByteString getSymbol1Uuid();

    /**
     * <code>optional bytes symbol2_uuid = 4;</code>
     */
    com.google.protobuf.ByteString getSymbol2Uuid();
  }
  /**
   * Protobuf type {@code proto.SymAddrAddr}
   */
  public  static final class SymAddrAddr extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SymAddrAddr)
      SymAddrAddrOrBuilder {
    // Use SymAddrAddr.newBuilder() to construct.
    private SymAddrAddr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SymAddrAddr() {
      scale_ = 0L;
      offset_ = 0L;
      symbol1Uuid_ = com.google.protobuf.ByteString.EMPTY;
      symbol2Uuid_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SymAddrAddr(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              scale_ = input.readInt64();
              break;
            }
            case 16: {

              offset_ = input.readInt64();
              break;
            }
            case 26: {

              symbol1Uuid_ = input.readBytes();
              break;
            }
            case 34: {

              symbol2Uuid_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrAddr_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrAddr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SymbolicExpressionOuterClass.SymAddrAddr.class, proto.SymbolicExpressionOuterClass.SymAddrAddr.Builder.class);
    }

    public static final int SCALE_FIELD_NUMBER = 1;
    private long scale_;
    /**
     * <code>optional int64 scale = 1;</code>
     */
    public long getScale() {
      return scale_;
    }

    public static final int OFFSET_FIELD_NUMBER = 2;
    private long offset_;
    /**
     * <code>optional int64 offset = 2;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int SYMBOL1_UUID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString symbol1Uuid_;
    /**
     * <code>optional bytes symbol1_uuid = 3;</code>
     */
    public com.google.protobuf.ByteString getSymbol1Uuid() {
      return symbol1Uuid_;
    }

    public static final int SYMBOL2_UUID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString symbol2Uuid_;
    /**
     * <code>optional bytes symbol2_uuid = 4;</code>
     */
    public com.google.protobuf.ByteString getSymbol2Uuid() {
      return symbol2Uuid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (scale_ != 0L) {
        output.writeInt64(1, scale_);
      }
      if (offset_ != 0L) {
        output.writeInt64(2, offset_);
      }
      if (!symbol1Uuid_.isEmpty()) {
        output.writeBytes(3, symbol1Uuid_);
      }
      if (!symbol2Uuid_.isEmpty()) {
        output.writeBytes(4, symbol2Uuid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (scale_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, scale_);
      }
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, offset_);
      }
      if (!symbol1Uuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, symbol1Uuid_);
      }
      if (!symbol2Uuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, symbol2Uuid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.SymbolicExpressionOuterClass.SymAddrAddr)) {
        return super.equals(obj);
      }
      proto.SymbolicExpressionOuterClass.SymAddrAddr other = (proto.SymbolicExpressionOuterClass.SymAddrAddr) obj;

      boolean result = true;
      result = result && (getScale()
          == other.getScale());
      result = result && (getOffset()
          == other.getOffset());
      result = result && getSymbol1Uuid()
          .equals(other.getSymbol1Uuid());
      result = result && getSymbol2Uuid()
          .equals(other.getSymbol2Uuid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SCALE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getScale());
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      hash = (37 * hash) + SYMBOL1_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol1Uuid().hashCode();
      hash = (37 * hash) + SYMBOL2_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol2Uuid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymAddrAddr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.SymbolicExpressionOuterClass.SymAddrAddr prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SymAddrAddr}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SymAddrAddr)
        proto.SymbolicExpressionOuterClass.SymAddrAddrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrAddr_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrAddr_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SymbolicExpressionOuterClass.SymAddrAddr.class, proto.SymbolicExpressionOuterClass.SymAddrAddr.Builder.class);
      }

      // Construct using proto.SymbolicExpressionOuterClass.SymAddrAddr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        scale_ = 0L;

        offset_ = 0L;

        symbol1Uuid_ = com.google.protobuf.ByteString.EMPTY;

        symbol2Uuid_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymAddrAddr_descriptor;
      }

      public proto.SymbolicExpressionOuterClass.SymAddrAddr getDefaultInstanceForType() {
        return proto.SymbolicExpressionOuterClass.SymAddrAddr.getDefaultInstance();
      }

      public proto.SymbolicExpressionOuterClass.SymAddrAddr build() {
        proto.SymbolicExpressionOuterClass.SymAddrAddr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SymbolicExpressionOuterClass.SymAddrAddr buildPartial() {
        proto.SymbolicExpressionOuterClass.SymAddrAddr result = new proto.SymbolicExpressionOuterClass.SymAddrAddr(this);
        result.scale_ = scale_;
        result.offset_ = offset_;
        result.symbol1Uuid_ = symbol1Uuid_;
        result.symbol2Uuid_ = symbol2Uuid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SymbolicExpressionOuterClass.SymAddrAddr) {
          return mergeFrom((proto.SymbolicExpressionOuterClass.SymAddrAddr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SymbolicExpressionOuterClass.SymAddrAddr other) {
        if (other == proto.SymbolicExpressionOuterClass.SymAddrAddr.getDefaultInstance()) return this;
        if (other.getScale() != 0L) {
          setScale(other.getScale());
        }
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (other.getSymbol1Uuid() != com.google.protobuf.ByteString.EMPTY) {
          setSymbol1Uuid(other.getSymbol1Uuid());
        }
        if (other.getSymbol2Uuid() != com.google.protobuf.ByteString.EMPTY) {
          setSymbol2Uuid(other.getSymbol2Uuid());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SymbolicExpressionOuterClass.SymAddrAddr parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SymbolicExpressionOuterClass.SymAddrAddr) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long scale_ ;
      /**
       * <code>optional int64 scale = 1;</code>
       */
      public long getScale() {
        return scale_;
      }
      /**
       * <code>optional int64 scale = 1;</code>
       */
      public Builder setScale(long value) {
        
        scale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 scale = 1;</code>
       */
      public Builder clearScale() {
        
        scale_ = 0L;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <code>optional int64 offset = 2;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>optional int64 offset = 2;</code>
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 offset = 2;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString symbol1Uuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes symbol1_uuid = 3;</code>
       */
      public com.google.protobuf.ByteString getSymbol1Uuid() {
        return symbol1Uuid_;
      }
      /**
       * <code>optional bytes symbol1_uuid = 3;</code>
       */
      public Builder setSymbol1Uuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol1Uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes symbol1_uuid = 3;</code>
       */
      public Builder clearSymbol1Uuid() {
        
        symbol1Uuid_ = getDefaultInstance().getSymbol1Uuid();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString symbol2Uuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes symbol2_uuid = 4;</code>
       */
      public com.google.protobuf.ByteString getSymbol2Uuid() {
        return symbol2Uuid_;
      }
      /**
       * <code>optional bytes symbol2_uuid = 4;</code>
       */
      public Builder setSymbol2Uuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol2Uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes symbol2_uuid = 4;</code>
       */
      public Builder clearSymbol2Uuid() {
        
        symbol2Uuid_ = getDefaultInstance().getSymbol2Uuid();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.SymAddrAddr)
    }

    // @@protoc_insertion_point(class_scope:proto.SymAddrAddr)
    private static final proto.SymbolicExpressionOuterClass.SymAddrAddr DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.SymbolicExpressionOuterClass.SymAddrAddr();
    }

    public static proto.SymbolicExpressionOuterClass.SymAddrAddr getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SymAddrAddr>
        PARSER = new com.google.protobuf.AbstractParser<SymAddrAddr>() {
      public SymAddrAddr parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SymAddrAddr(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SymAddrAddr> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SymAddrAddr> getParserForType() {
      return PARSER;
    }

    public proto.SymbolicExpressionOuterClass.SymAddrAddr getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SymbolicExpressionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SymbolicExpression)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.SymStackConst stack_const = 1;</code>
     */
    proto.SymbolicExpressionOuterClass.SymStackConst getStackConst();
    /**
     * <code>optional .proto.SymStackConst stack_const = 1;</code>
     */
    proto.SymbolicExpressionOuterClass.SymStackConstOrBuilder getStackConstOrBuilder();

    /**
     * <code>optional .proto.SymAddrConst addr_const = 2;</code>
     */
    proto.SymbolicExpressionOuterClass.SymAddrConst getAddrConst();
    /**
     * <code>optional .proto.SymAddrConst addr_const = 2;</code>
     */
    proto.SymbolicExpressionOuterClass.SymAddrConstOrBuilder getAddrConstOrBuilder();

    /**
     * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
     */
    proto.SymbolicExpressionOuterClass.SymAddrAddr getAddrAddr();
    /**
     * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
     */
    proto.SymbolicExpressionOuterClass.SymAddrAddrOrBuilder getAddrAddrOrBuilder();

    public proto.SymbolicExpressionOuterClass.SymbolicExpression.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code proto.SymbolicExpression}
   */
  public  static final class SymbolicExpression extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SymbolicExpression)
      SymbolicExpressionOrBuilder {
    // Use SymbolicExpression.newBuilder() to construct.
    private SymbolicExpression(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SymbolicExpression() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SymbolicExpression(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto.SymbolicExpressionOuterClass.SymStackConst.Builder subBuilder = null;
              if (valueCase_ == 1) {
                subBuilder = ((proto.SymbolicExpressionOuterClass.SymStackConst) value_).toBuilder();
              }
              value_ =
                  input.readMessage(proto.SymbolicExpressionOuterClass.SymStackConst.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((proto.SymbolicExpressionOuterClass.SymStackConst) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 1;
              break;
            }
            case 18: {
              proto.SymbolicExpressionOuterClass.SymAddrConst.Builder subBuilder = null;
              if (valueCase_ == 2) {
                subBuilder = ((proto.SymbolicExpressionOuterClass.SymAddrConst) value_).toBuilder();
              }
              value_ =
                  input.readMessage(proto.SymbolicExpressionOuterClass.SymAddrConst.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((proto.SymbolicExpressionOuterClass.SymAddrConst) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 2;
              break;
            }
            case 26: {
              proto.SymbolicExpressionOuterClass.SymAddrAddr.Builder subBuilder = null;
              if (valueCase_ == 3) {
                subBuilder = ((proto.SymbolicExpressionOuterClass.SymAddrAddr) value_).toBuilder();
              }
              value_ =
                  input.readMessage(proto.SymbolicExpressionOuterClass.SymAddrAddr.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((proto.SymbolicExpressionOuterClass.SymAddrAddr) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SymbolicExpressionOuterClass.internal_static_proto_SymbolicExpression_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SymbolicExpressionOuterClass.internal_static_proto_SymbolicExpression_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SymbolicExpressionOuterClass.SymbolicExpression.class, proto.SymbolicExpressionOuterClass.SymbolicExpression.Builder.class);
    }

    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite {
      STACK_CONST(1),
      ADDR_CONST(2),
      ADDR_ADDR(3),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 1: return STACK_CONST;
          case 2: return ADDR_CONST;
          case 3: return ADDR_ADDR;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int STACK_CONST_FIELD_NUMBER = 1;
    /**
     * <code>optional .proto.SymStackConst stack_const = 1;</code>
     */
    public proto.SymbolicExpressionOuterClass.SymStackConst getStackConst() {
      if (valueCase_ == 1) {
         return (proto.SymbolicExpressionOuterClass.SymStackConst) value_;
      }
      return proto.SymbolicExpressionOuterClass.SymStackConst.getDefaultInstance();
    }
    /**
     * <code>optional .proto.SymStackConst stack_const = 1;</code>
     */
    public proto.SymbolicExpressionOuterClass.SymStackConstOrBuilder getStackConstOrBuilder() {
      if (valueCase_ == 1) {
         return (proto.SymbolicExpressionOuterClass.SymStackConst) value_;
      }
      return proto.SymbolicExpressionOuterClass.SymStackConst.getDefaultInstance();
    }

    public static final int ADDR_CONST_FIELD_NUMBER = 2;
    /**
     * <code>optional .proto.SymAddrConst addr_const = 2;</code>
     */
    public proto.SymbolicExpressionOuterClass.SymAddrConst getAddrConst() {
      if (valueCase_ == 2) {
         return (proto.SymbolicExpressionOuterClass.SymAddrConst) value_;
      }
      return proto.SymbolicExpressionOuterClass.SymAddrConst.getDefaultInstance();
    }
    /**
     * <code>optional .proto.SymAddrConst addr_const = 2;</code>
     */
    public proto.SymbolicExpressionOuterClass.SymAddrConstOrBuilder getAddrConstOrBuilder() {
      if (valueCase_ == 2) {
         return (proto.SymbolicExpressionOuterClass.SymAddrConst) value_;
      }
      return proto.SymbolicExpressionOuterClass.SymAddrConst.getDefaultInstance();
    }

    public static final int ADDR_ADDR_FIELD_NUMBER = 3;
    /**
     * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
     */
    public proto.SymbolicExpressionOuterClass.SymAddrAddr getAddrAddr() {
      if (valueCase_ == 3) {
         return (proto.SymbolicExpressionOuterClass.SymAddrAddr) value_;
      }
      return proto.SymbolicExpressionOuterClass.SymAddrAddr.getDefaultInstance();
    }
    /**
     * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
     */
    public proto.SymbolicExpressionOuterClass.SymAddrAddrOrBuilder getAddrAddrOrBuilder() {
      if (valueCase_ == 3) {
         return (proto.SymbolicExpressionOuterClass.SymAddrAddr) value_;
      }
      return proto.SymbolicExpressionOuterClass.SymAddrAddr.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (valueCase_ == 1) {
        output.writeMessage(1, (proto.SymbolicExpressionOuterClass.SymStackConst) value_);
      }
      if (valueCase_ == 2) {
        output.writeMessage(2, (proto.SymbolicExpressionOuterClass.SymAddrConst) value_);
      }
      if (valueCase_ == 3) {
        output.writeMessage(3, (proto.SymbolicExpressionOuterClass.SymAddrAddr) value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (valueCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (proto.SymbolicExpressionOuterClass.SymStackConst) value_);
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (proto.SymbolicExpressionOuterClass.SymAddrConst) value_);
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (proto.SymbolicExpressionOuterClass.SymAddrAddr) value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.SymbolicExpressionOuterClass.SymbolicExpression)) {
        return super.equals(obj);
      }
      proto.SymbolicExpressionOuterClass.SymbolicExpression other = (proto.SymbolicExpressionOuterClass.SymbolicExpression) obj;

      boolean result = true;
      result = result && getValueCase().equals(
          other.getValueCase());
      if (!result) return false;
      switch (valueCase_) {
        case 1:
          result = result && getStackConst()
              .equals(other.getStackConst());
          break;
        case 2:
          result = result && getAddrConst()
              .equals(other.getAddrConst());
          break;
        case 3:
          result = result && getAddrAddr()
              .equals(other.getAddrAddr());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (valueCase_) {
        case 1:
          hash = (37 * hash) + STACK_CONST_FIELD_NUMBER;
          hash = (53 * hash) + getStackConst().hashCode();
          break;
        case 2:
          hash = (37 * hash) + ADDR_CONST_FIELD_NUMBER;
          hash = (53 * hash) + getAddrConst().hashCode();
          break;
        case 3:
          hash = (37 * hash) + ADDR_ADDR_FIELD_NUMBER;
          hash = (53 * hash) + getAddrAddr().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolicExpressionOuterClass.SymbolicExpression parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.SymbolicExpressionOuterClass.SymbolicExpression prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SymbolicExpression}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SymbolicExpression)
        proto.SymbolicExpressionOuterClass.SymbolicExpressionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymbolicExpression_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymbolicExpression_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SymbolicExpressionOuterClass.SymbolicExpression.class, proto.SymbolicExpressionOuterClass.SymbolicExpression.Builder.class);
      }

      // Construct using proto.SymbolicExpressionOuterClass.SymbolicExpression.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SymbolicExpressionOuterClass.internal_static_proto_SymbolicExpression_descriptor;
      }

      public proto.SymbolicExpressionOuterClass.SymbolicExpression getDefaultInstanceForType() {
        return proto.SymbolicExpressionOuterClass.SymbolicExpression.getDefaultInstance();
      }

      public proto.SymbolicExpressionOuterClass.SymbolicExpression build() {
        proto.SymbolicExpressionOuterClass.SymbolicExpression result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SymbolicExpressionOuterClass.SymbolicExpression buildPartial() {
        proto.SymbolicExpressionOuterClass.SymbolicExpression result = new proto.SymbolicExpressionOuterClass.SymbolicExpression(this);
        if (valueCase_ == 1) {
          if (stackConstBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = stackConstBuilder_.build();
          }
        }
        if (valueCase_ == 2) {
          if (addrConstBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = addrConstBuilder_.build();
          }
        }
        if (valueCase_ == 3) {
          if (addrAddrBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = addrAddrBuilder_.build();
          }
        }
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SymbolicExpressionOuterClass.SymbolicExpression) {
          return mergeFrom((proto.SymbolicExpressionOuterClass.SymbolicExpression)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SymbolicExpressionOuterClass.SymbolicExpression other) {
        if (other == proto.SymbolicExpressionOuterClass.SymbolicExpression.getDefaultInstance()) return this;
        switch (other.getValueCase()) {
          case STACK_CONST: {
            mergeStackConst(other.getStackConst());
            break;
          }
          case ADDR_CONST: {
            mergeAddrConst(other.getAddrConst());
            break;
          }
          case ADDR_ADDR: {
            mergeAddrAddr(other.getAddrAddr());
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SymbolicExpressionOuterClass.SymbolicExpression parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SymbolicExpressionOuterClass.SymbolicExpression) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          proto.SymbolicExpressionOuterClass.SymStackConst, proto.SymbolicExpressionOuterClass.SymStackConst.Builder, proto.SymbolicExpressionOuterClass.SymStackConstOrBuilder> stackConstBuilder_;
      /**
       * <code>optional .proto.SymStackConst stack_const = 1;</code>
       */
      public proto.SymbolicExpressionOuterClass.SymStackConst getStackConst() {
        if (stackConstBuilder_ == null) {
          if (valueCase_ == 1) {
            return (proto.SymbolicExpressionOuterClass.SymStackConst) value_;
          }
          return proto.SymbolicExpressionOuterClass.SymStackConst.getDefaultInstance();
        } else {
          if (valueCase_ == 1) {
            return stackConstBuilder_.getMessage();
          }
          return proto.SymbolicExpressionOuterClass.SymStackConst.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.SymStackConst stack_const = 1;</code>
       */
      public Builder setStackConst(proto.SymbolicExpressionOuterClass.SymStackConst value) {
        if (stackConstBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          stackConstBuilder_.setMessage(value);
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>optional .proto.SymStackConst stack_const = 1;</code>
       */
      public Builder setStackConst(
          proto.SymbolicExpressionOuterClass.SymStackConst.Builder builderForValue) {
        if (stackConstBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          stackConstBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>optional .proto.SymStackConst stack_const = 1;</code>
       */
      public Builder mergeStackConst(proto.SymbolicExpressionOuterClass.SymStackConst value) {
        if (stackConstBuilder_ == null) {
          if (valueCase_ == 1 &&
              value_ != proto.SymbolicExpressionOuterClass.SymStackConst.getDefaultInstance()) {
            value_ = proto.SymbolicExpressionOuterClass.SymStackConst.newBuilder((proto.SymbolicExpressionOuterClass.SymStackConst) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 1) {
            stackConstBuilder_.mergeFrom(value);
          }
          stackConstBuilder_.setMessage(value);
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>optional .proto.SymStackConst stack_const = 1;</code>
       */
      public Builder clearStackConst() {
        if (stackConstBuilder_ == null) {
          if (valueCase_ == 1) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 1) {
            valueCase_ = 0;
            value_ = null;
          }
          stackConstBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .proto.SymStackConst stack_const = 1;</code>
       */
      public proto.SymbolicExpressionOuterClass.SymStackConst.Builder getStackConstBuilder() {
        return getStackConstFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.SymStackConst stack_const = 1;</code>
       */
      public proto.SymbolicExpressionOuterClass.SymStackConstOrBuilder getStackConstOrBuilder() {
        if ((valueCase_ == 1) && (stackConstBuilder_ != null)) {
          return stackConstBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 1) {
            return (proto.SymbolicExpressionOuterClass.SymStackConst) value_;
          }
          return proto.SymbolicExpressionOuterClass.SymStackConst.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.SymStackConst stack_const = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.SymbolicExpressionOuterClass.SymStackConst, proto.SymbolicExpressionOuterClass.SymStackConst.Builder, proto.SymbolicExpressionOuterClass.SymStackConstOrBuilder> 
          getStackConstFieldBuilder() {
        if (stackConstBuilder_ == null) {
          if (!(valueCase_ == 1)) {
            value_ = proto.SymbolicExpressionOuterClass.SymStackConst.getDefaultInstance();
          }
          stackConstBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.SymbolicExpressionOuterClass.SymStackConst, proto.SymbolicExpressionOuterClass.SymStackConst.Builder, proto.SymbolicExpressionOuterClass.SymStackConstOrBuilder>(
                  (proto.SymbolicExpressionOuterClass.SymStackConst) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 1;
        onChanged();;
        return stackConstBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          proto.SymbolicExpressionOuterClass.SymAddrConst, proto.SymbolicExpressionOuterClass.SymAddrConst.Builder, proto.SymbolicExpressionOuterClass.SymAddrConstOrBuilder> addrConstBuilder_;
      /**
       * <code>optional .proto.SymAddrConst addr_const = 2;</code>
       */
      public proto.SymbolicExpressionOuterClass.SymAddrConst getAddrConst() {
        if (addrConstBuilder_ == null) {
          if (valueCase_ == 2) {
            return (proto.SymbolicExpressionOuterClass.SymAddrConst) value_;
          }
          return proto.SymbolicExpressionOuterClass.SymAddrConst.getDefaultInstance();
        } else {
          if (valueCase_ == 2) {
            return addrConstBuilder_.getMessage();
          }
          return proto.SymbolicExpressionOuterClass.SymAddrConst.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.SymAddrConst addr_const = 2;</code>
       */
      public Builder setAddrConst(proto.SymbolicExpressionOuterClass.SymAddrConst value) {
        if (addrConstBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          addrConstBuilder_.setMessage(value);
        }
        valueCase_ = 2;
        return this;
      }
      /**
       * <code>optional .proto.SymAddrConst addr_const = 2;</code>
       */
      public Builder setAddrConst(
          proto.SymbolicExpressionOuterClass.SymAddrConst.Builder builderForValue) {
        if (addrConstBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          addrConstBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 2;
        return this;
      }
      /**
       * <code>optional .proto.SymAddrConst addr_const = 2;</code>
       */
      public Builder mergeAddrConst(proto.SymbolicExpressionOuterClass.SymAddrConst value) {
        if (addrConstBuilder_ == null) {
          if (valueCase_ == 2 &&
              value_ != proto.SymbolicExpressionOuterClass.SymAddrConst.getDefaultInstance()) {
            value_ = proto.SymbolicExpressionOuterClass.SymAddrConst.newBuilder((proto.SymbolicExpressionOuterClass.SymAddrConst) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 2) {
            addrConstBuilder_.mergeFrom(value);
          }
          addrConstBuilder_.setMessage(value);
        }
        valueCase_ = 2;
        return this;
      }
      /**
       * <code>optional .proto.SymAddrConst addr_const = 2;</code>
       */
      public Builder clearAddrConst() {
        if (addrConstBuilder_ == null) {
          if (valueCase_ == 2) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 2) {
            valueCase_ = 0;
            value_ = null;
          }
          addrConstBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .proto.SymAddrConst addr_const = 2;</code>
       */
      public proto.SymbolicExpressionOuterClass.SymAddrConst.Builder getAddrConstBuilder() {
        return getAddrConstFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.SymAddrConst addr_const = 2;</code>
       */
      public proto.SymbolicExpressionOuterClass.SymAddrConstOrBuilder getAddrConstOrBuilder() {
        if ((valueCase_ == 2) && (addrConstBuilder_ != null)) {
          return addrConstBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 2) {
            return (proto.SymbolicExpressionOuterClass.SymAddrConst) value_;
          }
          return proto.SymbolicExpressionOuterClass.SymAddrConst.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.SymAddrConst addr_const = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.SymbolicExpressionOuterClass.SymAddrConst, proto.SymbolicExpressionOuterClass.SymAddrConst.Builder, proto.SymbolicExpressionOuterClass.SymAddrConstOrBuilder> 
          getAddrConstFieldBuilder() {
        if (addrConstBuilder_ == null) {
          if (!(valueCase_ == 2)) {
            value_ = proto.SymbolicExpressionOuterClass.SymAddrConst.getDefaultInstance();
          }
          addrConstBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.SymbolicExpressionOuterClass.SymAddrConst, proto.SymbolicExpressionOuterClass.SymAddrConst.Builder, proto.SymbolicExpressionOuterClass.SymAddrConstOrBuilder>(
                  (proto.SymbolicExpressionOuterClass.SymAddrConst) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 2;
        onChanged();;
        return addrConstBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          proto.SymbolicExpressionOuterClass.SymAddrAddr, proto.SymbolicExpressionOuterClass.SymAddrAddr.Builder, proto.SymbolicExpressionOuterClass.SymAddrAddrOrBuilder> addrAddrBuilder_;
      /**
       * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
       */
      public proto.SymbolicExpressionOuterClass.SymAddrAddr getAddrAddr() {
        if (addrAddrBuilder_ == null) {
          if (valueCase_ == 3) {
            return (proto.SymbolicExpressionOuterClass.SymAddrAddr) value_;
          }
          return proto.SymbolicExpressionOuterClass.SymAddrAddr.getDefaultInstance();
        } else {
          if (valueCase_ == 3) {
            return addrAddrBuilder_.getMessage();
          }
          return proto.SymbolicExpressionOuterClass.SymAddrAddr.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
       */
      public Builder setAddrAddr(proto.SymbolicExpressionOuterClass.SymAddrAddr value) {
        if (addrAddrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          addrAddrBuilder_.setMessage(value);
        }
        valueCase_ = 3;
        return this;
      }
      /**
       * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
       */
      public Builder setAddrAddr(
          proto.SymbolicExpressionOuterClass.SymAddrAddr.Builder builderForValue) {
        if (addrAddrBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          addrAddrBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 3;
        return this;
      }
      /**
       * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
       */
      public Builder mergeAddrAddr(proto.SymbolicExpressionOuterClass.SymAddrAddr value) {
        if (addrAddrBuilder_ == null) {
          if (valueCase_ == 3 &&
              value_ != proto.SymbolicExpressionOuterClass.SymAddrAddr.getDefaultInstance()) {
            value_ = proto.SymbolicExpressionOuterClass.SymAddrAddr.newBuilder((proto.SymbolicExpressionOuterClass.SymAddrAddr) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 3) {
            addrAddrBuilder_.mergeFrom(value);
          }
          addrAddrBuilder_.setMessage(value);
        }
        valueCase_ = 3;
        return this;
      }
      /**
       * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
       */
      public Builder clearAddrAddr() {
        if (addrAddrBuilder_ == null) {
          if (valueCase_ == 3) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 3) {
            valueCase_ = 0;
            value_ = null;
          }
          addrAddrBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
       */
      public proto.SymbolicExpressionOuterClass.SymAddrAddr.Builder getAddrAddrBuilder() {
        return getAddrAddrFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
       */
      public proto.SymbolicExpressionOuterClass.SymAddrAddrOrBuilder getAddrAddrOrBuilder() {
        if ((valueCase_ == 3) && (addrAddrBuilder_ != null)) {
          return addrAddrBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 3) {
            return (proto.SymbolicExpressionOuterClass.SymAddrAddr) value_;
          }
          return proto.SymbolicExpressionOuterClass.SymAddrAddr.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.SymAddrAddr addr_addr = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.SymbolicExpressionOuterClass.SymAddrAddr, proto.SymbolicExpressionOuterClass.SymAddrAddr.Builder, proto.SymbolicExpressionOuterClass.SymAddrAddrOrBuilder> 
          getAddrAddrFieldBuilder() {
        if (addrAddrBuilder_ == null) {
          if (!(valueCase_ == 3)) {
            value_ = proto.SymbolicExpressionOuterClass.SymAddrAddr.getDefaultInstance();
          }
          addrAddrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.SymbolicExpressionOuterClass.SymAddrAddr, proto.SymbolicExpressionOuterClass.SymAddrAddr.Builder, proto.SymbolicExpressionOuterClass.SymAddrAddrOrBuilder>(
                  (proto.SymbolicExpressionOuterClass.SymAddrAddr) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 3;
        onChanged();;
        return addrAddrBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.SymbolicExpression)
    }

    // @@protoc_insertion_point(class_scope:proto.SymbolicExpression)
    private static final proto.SymbolicExpressionOuterClass.SymbolicExpression DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.SymbolicExpressionOuterClass.SymbolicExpression();
    }

    public static proto.SymbolicExpressionOuterClass.SymbolicExpression getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SymbolicExpression>
        PARSER = new com.google.protobuf.AbstractParser<SymbolicExpression>() {
      public SymbolicExpression parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SymbolicExpression(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SymbolicExpression> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SymbolicExpression> getParserForType() {
      return PARSER;
    }

    public proto.SymbolicExpressionOuterClass.SymbolicExpression getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SymStackConst_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SymStackConst_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SymAddrConst_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SymAddrConst_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SymAddrAddr_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SymAddrAddr_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SymbolicExpression_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SymbolicExpression_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030SymbolicExpression.proto\022\005proto\"4\n\rSym" +
      "StackConst\022\016\n\006offset\030\001 \001(\005\022\023\n\013symbol_uui" +
      "d\030\002 \001(\014\"3\n\014SymAddrConst\022\016\n\006offset\030\001 \001(\003\022" +
      "\023\n\013symbol_uuid\030\002 \001(\014\"X\n\013SymAddrAddr\022\r\n\005s" +
      "cale\030\001 \001(\003\022\016\n\006offset\030\002 \001(\003\022\024\n\014symbol1_uu" +
      "id\030\003 \001(\014\022\024\n\014symbol2_uuid\030\004 \001(\014\"\236\001\n\022Symbo" +
      "licExpression\022+\n\013stack_const\030\001 \001(\0132\024.pro" +
      "to.SymStackConstH\000\022)\n\naddr_const\030\002 \001(\0132\023" +
      ".proto.SymAddrConstH\000\022\'\n\taddr_addr\030\003 \001(\013" +
      "2\022.proto.SymAddrAddrH\000B\007\n\005valueb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_SymStackConst_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_SymStackConst_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SymStackConst_descriptor,
        new java.lang.String[] { "Offset", "SymbolUuid", });
    internal_static_proto_SymAddrConst_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SymAddrConst_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SymAddrConst_descriptor,
        new java.lang.String[] { "Offset", "SymbolUuid", });
    internal_static_proto_SymAddrAddr_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_SymAddrAddr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SymAddrAddr_descriptor,
        new java.lang.String[] { "Scale", "Offset", "Symbol1Uuid", "Symbol2Uuid", });
    internal_static_proto_SymbolicExpression_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_SymbolicExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SymbolicExpression_descriptor,
        new java.lang.String[] { "StackConst", "AddrConst", "AddrAddr", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
