// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Symbol.proto

package proto;

public final class SymbolOuterClass {
  private SymbolOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.StorageKind}
   */
  public enum StorageKind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Storage_Undefined = 0;</code>
     */
    Storage_Undefined(0),
    /**
     * <code>Storage_Normal = 1;</code>
     */
    Storage_Normal(1),
    /**
     * <code>Storage_Static = 2;</code>
     */
    Storage_Static(2),
    /**
     * <code>Storage_Extern = 3;</code>
     */
    Storage_Extern(3),
    /**
     * <code>Storage_Local = 4;</code>
     */
    Storage_Local(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Storage_Undefined = 0;</code>
     */
    public static final int Storage_Undefined_VALUE = 0;
    /**
     * <code>Storage_Normal = 1;</code>
     */
    public static final int Storage_Normal_VALUE = 1;
    /**
     * <code>Storage_Static = 2;</code>
     */
    public static final int Storage_Static_VALUE = 2;
    /**
     * <code>Storage_Extern = 3;</code>
     */
    public static final int Storage_Extern_VALUE = 3;
    /**
     * <code>Storage_Local = 4;</code>
     */
    public static final int Storage_Local_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StorageKind valueOf(int value) {
      return forNumber(value);
    }

    public static StorageKind forNumber(int value) {
      switch (value) {
        case 0: return Storage_Undefined;
        case 1: return Storage_Normal;
        case 2: return Storage_Static;
        case 3: return Storage_Extern;
        case 4: return Storage_Local;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StorageKind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StorageKind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StorageKind>() {
            public StorageKind findValueByNumber(int number) {
              return StorageKind.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.SymbolOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final StorageKind[] VALUES = values();

    public static StorageKind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StorageKind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.StorageKind)
  }

  public interface SymbolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Symbol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes uuid = 1;</code>
     */
    com.google.protobuf.ByteString getUuid();

    /**
     * <code>optional uint64 value = 2;</code>
     */
    long getValue();

    /**
     * <code>optional bytes referent_uuid = 5;</code>
     */
    com.google.protobuf.ByteString getReferentUuid();

    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .proto.StorageKind storage_kind = 4;</code>
     */
    int getStorageKindValue();
    /**
     * <code>optional .proto.StorageKind storage_kind = 4;</code>
     */
    proto.SymbolOuterClass.StorageKind getStorageKind();

    public proto.SymbolOuterClass.Symbol.OptionalPayloadCase getOptionalPayloadCase();
  }
  /**
   * Protobuf type {@code proto.Symbol}
   */
  public  static final class Symbol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Symbol)
      SymbolOrBuilder {
    // Use Symbol.newBuilder() to construct.
    private Symbol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Symbol() {
      uuid_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
      storageKind_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Symbol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              uuid_ = input.readBytes();
              break;
            }
            case 16: {
              optionalPayloadCase_ = 2;
              optionalPayload_ = input.readUInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              storageKind_ = rawValue;
              break;
            }
            case 42: {
              optionalPayloadCase_ = 5;
              optionalPayload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SymbolOuterClass.internal_static_proto_Symbol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SymbolOuterClass.internal_static_proto_Symbol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SymbolOuterClass.Symbol.class, proto.SymbolOuterClass.Symbol.Builder.class);
    }

    private int optionalPayloadCase_ = 0;
    private java.lang.Object optionalPayload_;
    public enum OptionalPayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      VALUE(2),
      REFERENT_UUID(5),
      OPTIONALPAYLOAD_NOT_SET(0);
      private final int value;
      private OptionalPayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static OptionalPayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static OptionalPayloadCase forNumber(int value) {
        switch (value) {
          case 2: return VALUE;
          case 5: return REFERENT_UUID;
          case 0: return OPTIONALPAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public OptionalPayloadCase
    getOptionalPayloadCase() {
      return OptionalPayloadCase.forNumber(
          optionalPayloadCase_);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString uuid_;
    /**
     * <code>optional bytes uuid = 1;</code>
     */
    public com.google.protobuf.ByteString getUuid() {
      return uuid_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    /**
     * <code>optional uint64 value = 2;</code>
     */
    public long getValue() {
      if (optionalPayloadCase_ == 2) {
        return (java.lang.Long) optionalPayload_;
      }
      return 0L;
    }

    public static final int REFERENT_UUID_FIELD_NUMBER = 5;
    /**
     * <code>optional bytes referent_uuid = 5;</code>
     */
    public com.google.protobuf.ByteString getReferentUuid() {
      if (optionalPayloadCase_ == 5) {
        return (com.google.protobuf.ByteString) optionalPayload_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STORAGE_KIND_FIELD_NUMBER = 4;
    private int storageKind_;
    /**
     * <code>optional .proto.StorageKind storage_kind = 4;</code>
     */
    public int getStorageKindValue() {
      return storageKind_;
    }
    /**
     * <code>optional .proto.StorageKind storage_kind = 4;</code>
     */
    public proto.SymbolOuterClass.StorageKind getStorageKind() {
      proto.SymbolOuterClass.StorageKind result = proto.SymbolOuterClass.StorageKind.valueOf(storageKind_);
      return result == null ? proto.SymbolOuterClass.StorageKind.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!uuid_.isEmpty()) {
        output.writeBytes(1, uuid_);
      }
      if (optionalPayloadCase_ == 2) {
        output.writeUInt64(
            2, (long)((java.lang.Long) optionalPayload_));
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (storageKind_ != proto.SymbolOuterClass.StorageKind.Storage_Undefined.getNumber()) {
        output.writeEnum(4, storageKind_);
      }
      if (optionalPayloadCase_ == 5) {
        output.writeBytes(
            5, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) optionalPayload_));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!uuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, uuid_);
      }
      if (optionalPayloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(
              2, (long)((java.lang.Long) optionalPayload_));
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (storageKind_ != proto.SymbolOuterClass.StorageKind.Storage_Undefined.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, storageKind_);
      }
      if (optionalPayloadCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              5, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) optionalPayload_));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.SymbolOuterClass.Symbol)) {
        return super.equals(obj);
      }
      proto.SymbolOuterClass.Symbol other = (proto.SymbolOuterClass.Symbol) obj;

      boolean result = true;
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && getName()
          .equals(other.getName());
      result = result && storageKind_ == other.storageKind_;
      result = result && getOptionalPayloadCase().equals(
          other.getOptionalPayloadCase());
      if (!result) return false;
      switch (optionalPayloadCase_) {
        case 2:
          result = result && (getValue()
              == other.getValue());
          break;
        case 5:
          result = result && getReferentUuid()
              .equals(other.getReferentUuid());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + STORAGE_KIND_FIELD_NUMBER;
      hash = (53 * hash) + storageKind_;
      switch (optionalPayloadCase_) {
        case 2:
          hash = (37 * hash) + VALUE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getValue());
          break;
        case 5:
          hash = (37 * hash) + REFERENT_UUID_FIELD_NUMBER;
          hash = (53 * hash) + getReferentUuid().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.SymbolOuterClass.Symbol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolOuterClass.Symbol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolOuterClass.Symbol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SymbolOuterClass.Symbol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SymbolOuterClass.Symbol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolOuterClass.Symbol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolOuterClass.Symbol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.SymbolOuterClass.Symbol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.SymbolOuterClass.Symbol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.SymbolOuterClass.Symbol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.SymbolOuterClass.Symbol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Symbol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Symbol)
        proto.SymbolOuterClass.SymbolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SymbolOuterClass.internal_static_proto_Symbol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SymbolOuterClass.internal_static_proto_Symbol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SymbolOuterClass.Symbol.class, proto.SymbolOuterClass.Symbol.Builder.class);
      }

      // Construct using proto.SymbolOuterClass.Symbol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = com.google.protobuf.ByteString.EMPTY;

        name_ = "";

        storageKind_ = 0;

        optionalPayloadCase_ = 0;
        optionalPayload_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SymbolOuterClass.internal_static_proto_Symbol_descriptor;
      }

      public proto.SymbolOuterClass.Symbol getDefaultInstanceForType() {
        return proto.SymbolOuterClass.Symbol.getDefaultInstance();
      }

      public proto.SymbolOuterClass.Symbol build() {
        proto.SymbolOuterClass.Symbol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SymbolOuterClass.Symbol buildPartial() {
        proto.SymbolOuterClass.Symbol result = new proto.SymbolOuterClass.Symbol(this);
        result.uuid_ = uuid_;
        if (optionalPayloadCase_ == 2) {
          result.optionalPayload_ = optionalPayload_;
        }
        if (optionalPayloadCase_ == 5) {
          result.optionalPayload_ = optionalPayload_;
        }
        result.name_ = name_;
        result.storageKind_ = storageKind_;
        result.optionalPayloadCase_ = optionalPayloadCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SymbolOuterClass.Symbol) {
          return mergeFrom((proto.SymbolOuterClass.Symbol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SymbolOuterClass.Symbol other) {
        if (other == proto.SymbolOuterClass.Symbol.getDefaultInstance()) return this;
        if (other.getUuid() != com.google.protobuf.ByteString.EMPTY) {
          setUuid(other.getUuid());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.storageKind_ != 0) {
          setStorageKindValue(other.getStorageKindValue());
        }
        switch (other.getOptionalPayloadCase()) {
          case VALUE: {
            setValue(other.getValue());
            break;
          }
          case REFERENT_UUID: {
            setReferentUuid(other.getReferentUuid());
            break;
          }
          case OPTIONALPAYLOAD_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SymbolOuterClass.Symbol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SymbolOuterClass.Symbol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int optionalPayloadCase_ = 0;
      private java.lang.Object optionalPayload_;
      public OptionalPayloadCase
          getOptionalPayloadCase() {
        return OptionalPayloadCase.forNumber(
            optionalPayloadCase_);
      }

      public Builder clearOptionalPayload() {
        optionalPayloadCase_ = 0;
        optionalPayload_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes uuid = 1;</code>
       */
      public com.google.protobuf.ByteString getUuid() {
        return uuid_;
      }
      /**
       * <code>optional bytes uuid = 1;</code>
       */
      public Builder setUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes uuid = 1;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }

      /**
       * <code>optional uint64 value = 2;</code>
       */
      public long getValue() {
        if (optionalPayloadCase_ == 2) {
          return (java.lang.Long) optionalPayload_;
        }
        return 0L;
      }
      /**
       * <code>optional uint64 value = 2;</code>
       */
      public Builder setValue(long value) {
        optionalPayloadCase_ = 2;
        optionalPayload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 value = 2;</code>
       */
      public Builder clearValue() {
        if (optionalPayloadCase_ == 2) {
          optionalPayloadCase_ = 0;
          optionalPayload_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional bytes referent_uuid = 5;</code>
       */
      public com.google.protobuf.ByteString getReferentUuid() {
        if (optionalPayloadCase_ == 5) {
          return (com.google.protobuf.ByteString) optionalPayload_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>optional bytes referent_uuid = 5;</code>
       */
      public Builder setReferentUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  optionalPayloadCase_ = 5;
        optionalPayload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes referent_uuid = 5;</code>
       */
      public Builder clearReferentUuid() {
        if (optionalPayloadCase_ == 5) {
          optionalPayloadCase_ = 0;
          optionalPayload_ = null;
          onChanged();
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int storageKind_ = 0;
      /**
       * <code>optional .proto.StorageKind storage_kind = 4;</code>
       */
      public int getStorageKindValue() {
        return storageKind_;
      }
      /**
       * <code>optional .proto.StorageKind storage_kind = 4;</code>
       */
      public Builder setStorageKindValue(int value) {
        storageKind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.StorageKind storage_kind = 4;</code>
       */
      public proto.SymbolOuterClass.StorageKind getStorageKind() {
        proto.SymbolOuterClass.StorageKind result = proto.SymbolOuterClass.StorageKind.valueOf(storageKind_);
        return result == null ? proto.SymbolOuterClass.StorageKind.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .proto.StorageKind storage_kind = 4;</code>
       */
      public Builder setStorageKind(proto.SymbolOuterClass.StorageKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        storageKind_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.StorageKind storage_kind = 4;</code>
       */
      public Builder clearStorageKind() {
        
        storageKind_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Symbol)
    }

    // @@protoc_insertion_point(class_scope:proto.Symbol)
    private static final proto.SymbolOuterClass.Symbol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.SymbolOuterClass.Symbol();
    }

    public static proto.SymbolOuterClass.Symbol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Symbol>
        PARSER = new com.google.protobuf.AbstractParser<Symbol>() {
      public Symbol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Symbol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Symbol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Symbol> getParserForType() {
      return PARSER;
    }

    public proto.SymbolOuterClass.Symbol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Symbol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Symbol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Symbol.proto\022\005proto\"\214\001\n\006Symbol\022\014\n\004uuid" +
      "\030\001 \001(\014\022\017\n\005value\030\002 \001(\004H\000\022\027\n\rreferent_uuid" +
      "\030\005 \001(\014H\000\022\014\n\004name\030\003 \001(\t\022(\n\014storage_kind\030\004" +
      " \001(\0162\022.proto.StorageKindB\022\n\020optional_pay" +
      "load*s\n\013StorageKind\022\025\n\021Storage_Undefined" +
      "\020\000\022\022\n\016Storage_Normal\020\001\022\022\n\016Storage_Static" +
      "\020\002\022\022\n\016Storage_Extern\020\003\022\021\n\rStorage_Local\020" +
      "\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Symbol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Symbol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Symbol_descriptor,
        new java.lang.String[] { "Uuid", "Value", "ReferentUuid", "Name", "StorageKind", "OptionalPayload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
